### ISSUE TITLE
Chat (Gitter) for Eleventy

### ISSUE THREAD

**Issue by miohtama** [11ty/eleventy#835] opened 2019-12-26 11:42 UTC
**Is your feature request related to a problem? Please describe.**

Currently Eleventy offers extensive documentation. StackOverflow works for getting answers. But for help or more opinioned discussion, like how to set up a JavaScript transformation pipeline, there is no good medium of discussion.

**Describe the solution you'd like**

Many open source projects use Gitter for setting up a chat where project users can join and senior users can share their wisdow with newcomers:

https://gitter.im/

It provides a single click integration for open source Github repos.

**Describe alternatives you've considered**

Popular alternatives may include

* IRC
* Matrix
* Discourse 

However those mediums are not so developer focused.

**Comment by DirtyF** [comment] 2019-12-26 14:11
The problems with chats, it that the answers get lost and are not indexed by search engines, and new comers will ask the same questions again and again. Discourse would be a better alternative IMHO.

This looks like a duplicate of a former similar issue.

**Comment by KlausDevWalker** [comment] 2019-12-27 22:31
If I can give my 2 cents, what do you think about a Telegram group? It's dynamic, it allows up to 200K people, searchable chat history, granular admins permissions, etc. 

I made an account there to prevent trolls to take another name (@eleventy was already taken - say the support if you have the same ID on other 3 social media, they can help you "regain" that) and put it at t.me/Eleventy_11ty (a username can't start with numbers and can carries only numbers, letters and underscores). t.me/SSG_11ty is also available.

If you think it's a good idea I can handle the ownership to you or anybody of your choice. I just think it's a good idea to merge those two communities :) Let me know about that.

**Comment by DirtyF** [comment] 2019-12-27 23:05
Found the original discussion on https://github.com/11ty/eleventy-community/issues/4

**Comment by KlausDevWalker** [comment] 2019-12-28 14:38
> Please read former discussion on [11ty/eleventy-community#4](https://github.com/11ty/eleventy-community/issues/4)

Good. I read it. Thanks for replying.

**Comment by zachleat** [comment] 2019-12-29 20:40
Ah hmm—I was not tuned into these Telegram options—thanks! I added both Gitter and Telegram to https://github.com/11ty/eleventy-community/issues/4#issuecomment-569540016

Please follow along over there—thanks!

**Closed by zachleat** 2019-12-29 20:40 UTC
Labels: enhancement

**Comment by KlausDevWalker** [comment] 2019-12-29 22:14
@zachleat Great! I've just subscribed there. I must mention that I edited my reply above to add some other Telegram feature that may interest you. I wish the best for this great tool Eleventy is. See ya :D
