### ISSUE TITLE
clean up parameter

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1233] opened 2020-06-05 04:17 UTC
Similar to how [metalsmith ](https://metalsmith.io/) handles it, have a parameter you can pass e.g. `--clean` that deletes `_site` or the directory the user supplied in `.eleventy.js` before compiling a new state:

```javascript
.clean(true)                // clean destination before
```

This would apply to `--serve` too.

That would allow to e.g. during development if you frequently change the folder structure through paginations, not have to do it yourself.

**Comment by zachleat** [comment] 2020-06-08 01:59
Duplicate of feature request at #19

**Comment by zachleat** [comment] 2020-06-08 01:59
(please upvote over there!)

**Closed by zachleat** 2020-06-08 01:59 UTC
Labels: duplicate, enhancement
