### ISSUE TITLE
Build only files that have changed

### ISSUE THREAD

**Issue by jaime8111** [11ty/eleventy#825] opened 2019-12-16 12:32 UTC
Every time a build my site with 11ty **all the files are built again, even if they have no changed since the last build process**.

I have a Google Cloud rsync process to upload all the files that have changed to my production environment. Now Google thinks that all the files have changed every time i build the site, because the date of the files are newer. 

The **expected behavior is that 11ty detect if each file is on the destiny folder, compare them, and only update it if their content is different**.

**Is it possible to do it now? If not, anyone knows any gulp process to get this done**. Maybe to build on a temporal folder, and then compare the content of every file on temporal and build folder?

Thanks!

**Comment by DirtyF** [comment] 2019-12-16 12:54
Duplicate of #108

**Comment by zachleat** [comment] 2019-12-29 04:39
Thanks @DirtyF! Yep this is a dupe, sorry! Follow along at #108

**Closed by zachleat** 2019-12-29 04:39 UTC
Labels: duplicate
