### ISSUE TITLE
👍👎 Tag like syntax for `eleventyExcludeFromCollections` to exclude page from specific tag's collection

### ISSUE THREAD

**Issue by nitin2953** [11ty/eleventy#2287] opened 2022-03-25 08:10 UTC
https://discord.com/channels/741017160297611315/872911930120110190/956590310987792414

<details>
<summary>As discussed in above discord thread</summary>

> My file structure
> ```
> blog
>  ├─ 1st-post.md
>  ├─ 2nd-post.md
>  ├─ 3rd-post.md
>  ├─ blog.json
>  └─ index.njk
> ```
> `blog.json`
> ```json
> {
>     "layout": "post.njk",
>     "tags": "blog_post"
> }
> ```
> `index.njk`
> ```hbs
> {%- for post in collections.blog_post -%}
>     <h2>{{ post.data.title }}</h2>
>     <p>{{ post.data.description }}</p>
>     <a href="{{ post.url }}">Read more</a>
> {% endfor -%}
> ```
> `_site/blog/index.html`
> ```html
> <h2>Blog</h2> ◀◀◀
> ...
> <h2>1st Post</h2>
> ...
> <h2>2nd Post</h2>
> ...
> <h2>3rd Post</h2>
> ...
> ```
> 
> **Problem:**
> I want to exclude `blog/index.njk` ONLY form `collections.blog_post`
> I can't set `eleventyExcludeFromCollections: true` since I want it in `sitemap.xml` which is using `collections.all`
> 
> **Solution:**
> New option for `eleventyExcludeFromCollections` with syntax like https://11ty.dev/docs/collections/#tag-syntax.
> e.g. `eleventyExcludeFromCollections: blog_post` for excluding `blog/index.njk` ONLY from `collections.blog_post`
> 
> **Edit 1: Another Solution**
> Moving `blog/index.njk` to parent folder (and adding `permalink: /blog/` in front matter) will stop adding `blog/blog.json`'s tag to it & it won't include it in it's collection.
> 
> **Edit 2:**
> BUT this feels hacky & will mess files structure in future.

</details>

 
**Problem**
- `eleventyExcludeFromCollections: true` remove page from all collections including `collections.all`.
- I want to exclude `index.njk` file (which is residing with `<dir>.json` file) ONLY from `collections.blog_post` OR any specific collection except `collections.all` which is used `sitemap.xml`.

**Solution**
**New option for `eleventyExcludeFromCollections` with [tag like syntax](https://11ty.dev/docs/collections/#tag-syntax).**
e.g. Setting `eleventyExcludeFromCollections: blog_post` in `blog/index.njk` for excluding it ONLY from `collections.blog_post`.

**Alternatives**
1. Move `blog/index.njk` file to \<parent\> folder and add `permalink: /blog/` in it's front matter.
2. Opt out from `DataDeepMerge` then add `tags: null`.
3. Add `override:tags: null` (without opting out from `DataDeepMerge`) to remove it from all tag's collections.
	But if I want to include it in new tag's collection, I will have to update the \<tag\> in `override:tags` whenever I create a new tag collection.

**Additional context**
If 11ty go with tag like syntax for `eleventyExcludeFromCollections` then, **reserve `all` value for excluding page from `collections.all` but keeping in every other collection.**

\---

👍👎 Vote for it

**Comment by pdehaan** [comment] 2022-03-25 19:26
See also:
- https://github.com/11ty/eleventy/issues/1175

**Comment by thisisgonnatakeawhile** [comment] 2022-04-25 20:48
I was just looking into how to do the exact same thing. It'd be very useful to have an option like the one you're proposing so thumbs up and here's hoping!

**Comment by nitin2953** [comment] 2022-04-26 10:42
Left: More mess | Right: Less mess

![vsocdeX_cx_cx](https://user-images.githubusercontent.com/34852979/165282818-5f2cf6d1-32ca-49d1-aa63-7e0bc24fcc7f.png)

**Comment by zachleat** [comment] 2022-07-01 19:56
I think this is a duplicate of https://github.com/11ty/eleventy/issues/1175 Please follow along over there!

**Closed by zachleat** 2022-07-01 19:56 UTC
Labels: duplicate, enhancement, feature: 📞 collections

**Comment by zachleat** [comment] 2023-11-10 22:17
#2482 was merged and this will ship with 3.0.
