### ISSUE TITLE
How to delete files from _site before build

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#1090] opened 2020-04-12 07:02 UTC
Hi.

I've found myself several times shortly stuck on small issues before realizing that there are no actual issues but old files in the `_site` folder messing with me.
For example, if I change `permalink` in frontmatter, the `_site` folder will end up with both, old and new pages and browser refresh will be showing an old page that should not be there anymore. Not sure at all, but I'm afraid that this could lead to problems with Netlify's `dist` folder as well.

Is there a way to completely remove `_site` folder before each build? I was working with Gridsome and Nuxt.js on previous SSG projects and I believe that they are both creating a `dist` folder from the scratch on each build.

Thank you for your time and effort put in building such a wonderful tool.

Cheer.

**Comment by Ryuno-Ki** [comment] 2020-04-12 10:59
Duplicate of #19.
See also #744

**Comment by WebShapedBiz** [comment] 2020-04-12 12:17
Thank you @Ryuno-Ki and sorry for the duplicate, I've searched but obviously with wrong keywords.

Cheers.

**Comment by Ryuno-Ki** [comment] 2020-04-12 12:22
No worries. As you can see, you're not the first one. Would you mind to close this issue then?

**Closed** 2020-04-12 12:22 UTC
Labels: education

**Comment by Ryuno-Ki** [comment] 2020-04-12 12:27
(Perhaps worth to upvote #19 so it ranks higher in the enhancement queue - as you can tell, it's quite old).

Thanks for closing this issue!
