### ISSUE TITLE
Provide in-browser feedback when templates have a syntax error

### ISSUE THREAD

**Issue by stowball** [11ty/eleventy#542] opened 2019-05-25 10:31 UTC
Currently, unless you're watching the terminal output on every save, you have no idea if you've accidentally introduced a syntax error to your templates because for all intents and purposes, the browser reloads and appears to have worked. Unfortunately, it just reloads with the last good, cached version, which then causes extra frustration as you try to debug new code which you think should be rendered, but isn't.

Here's an example of what happens on an "unsuccessful" save:

```sh
File changed: _includes/components/header/link-level-1.ejs
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering ejs template ./style-guide/header.ejs (TemplateContentRenderError)
> ./style-guide/header.ejs:2
    1|
 >> 2| <%- include('../_includes/components/header/index'); %>

…

Processed 0 files in 0.03 seconds
Watching…
[Browsersync] Reloading Browsers...
```

which, apart from the number of files processed, is essentially the same as what happens on a successful save.

What I'd like to see is something like what Create React App does, where the error is logged to both the terminal and the browser, like this:

![image](https://user-images.githubusercontent.com/853552/58368117-d5468280-7f2b-11e9-9111-297e40e03e87.png)

**Comment by Ryuno-Ki** [comment] 2019-05-26 20:04
Duplicate of #525?

**Comment by stowball** [comment] 2019-05-26 22:55
It's similar for sure, although mine has a preferred suggestion of displaying the errors

**Comment by zachleat** [comment] 2019-05-29 02:07
Ah thanks @Ryuno-Ki I had forgotten about #525. Can we coalesce around that one @stowball? Maybe copy your comment wholesale? I do like your example screenshot very much

**Comment by zachleat** [comment] 2019-05-29 02:09
Going to close this as a duplicate for now. I like that there is more than one person making this request—thank you

**Closed by zachleat** 2019-05-29 02:09 UTC
Labels: duplicate, enhancement
