### ISSUE TITLE
Modifying a layout file only updates the output once in serve mode.

### ISSUE THREAD

**Issue by vuolen** [11ty/eleventy#2732] opened 2023-01-06 17:36 UTC
### Operating system

Ubuntu 18.04.6 LTS

### Eleventy

2.0.0-canary.24

### Describe the bug

My project consists of a template called `index.njk` that uses a layout `layout.njk`.

When I run `eleventy --serve` and update the layout once, the changes are hot reloaded into my browser.

However any subsequent changes do not show in my browser even after a refresh. The only fix is to kill the eleventy process and start it again.

### Reproduction steps

1. Clone `https://github.com/osakunta/website/tree/eleventy_bug`
2. `cd ssg`
3. `yarn install`
4. `yarn dev:eleventy`
5. Go to localhost:8080
6. Change `src/site/_include/layouts/layout.njk`, do this a few times
7. Notice that the changes do not appear in the browser

### Expected behavior

For the changes to appear in the browser

### Reproduction URL

https://github.com/osakunta/website/tree/eleventy_bug

**Comment by vuolen** [comment] 2023-01-06 17:42
I narrowed this bug down to `TemplateCache.js`. It uses different keys for adding and removing.

`add`:
```
    if ("getFullKey" in layoutTemplate) {
      let fullKey = layoutTemplate.getFullKey();
      keys.add(fullKey)
    }

    if ("getKey" in layoutTemplate) {
      // if `key` was an alias, also set to the pathed layout value too
      // e.g. `layout: "default"` and `layout: "default.liquid"` will both map to the same template.
      keys.add(layoutTemplate.getKey());
    }

    for (let key of keys) {
      this.cache[key] = layoutTemplate;
    }
```

`remove`:
```
    let keys = layoutTemplate.getCacheKeys();
    for (let key of keys) {
      delete this.cache[key];
    }
```

**Comment by zachleat** [comment] 2023-01-06 21:29
Hey, I believe this is a duplicate of #2717 though I will look at your suggestion here!

Please subscribe over there, thanks!

**Closed** 2023-01-06 21:29 UTC
Labels: duplicate, release: canary
