### ISSUE TITLE
404 for passthrough resources after dev server hotreload

### ISSUE THREAD

**Issue by sebthom** [11ty/eleventy#2590] opened 2022-10-05 21:03 UTC
**Describe the bug**
I am starting the dev server and can browse the site. Everything loads.
The moment I change a HTML/Markdown file and eleventy reloads/rebuilds,
Images, Fonts, etc. are not accessible anymore in the browser and 404 is returned.

**To Reproduce**

1. Start the dev server
2. Open page in browser
3. Edit a content file
4. Images are not loaded in browser anymore

**Expected behavior**
Passthrough resources are still available after hotreload

**Screenshots**
Debug output after reload was triggered via file modification.
![image](https://user-images.githubusercontent.com/426959/194162937-f40d0eca-f7fb-447c-b445-e68bdc30c419.png)

**Environment:**

- OS and Version: Windows 10
- Eleventy Version: 2.0.0-canary.16

**Additional context**
My config looks something like this:
```js
// https://github.com/11ty/eleventy/blob/master/src/eleventyConfig.js
module.exports = function(eleventyConfig) {

    // https://www.11ty.dev/docs/config/#default-template-engine-for-global-data-files
    const config = {
        dir: {
            output: "dist",
            input: "site",
            includes: "_includes",
            data: "data"
        },
        passthrougFileCopy: true,

        /* Use NunJucks Template Engine
         * https://www.11ty.dev/docs/languages/nunjucks/
         */
        dataTemplateEngine: "njk",
        htmlTemplateEngine: "njk",
        markdownTemplateEngine: "njk",

        templateFormats: ["html", "md"]
    }

    // https://www.11ty.dev/docs/watch-serve/#eleventy-dev-server
    eleventyConfig.setServerOptions({
        port: 8080,
        showAllHosts: true,
    })

    /* configure template engine
     * https://www.11ty.dev/docs/languages/nunjucks/
     */
    eleventyConfig.setNunjucksEnvironmentOptions({
        throwOnUndefined: true
    })

    eleventyConfig.addPassthroughCopy('site/fonts/**/*.woff*')
    eleventyConfig.addPassthroughCopy('site/img/**/*.gif')
    eleventyConfig.addPassthroughCopy('site/img/**/*.png')
    eleventyConfig.addPassthroughCopy('site/img/**/*.svg')

    return config
}
```

Directory structure:
```
my-site/
	- dist/
	- site/
		- _includes/*.html
		- en/*.md
		- css/*.scss
		- fonts/*.woff
		- img/*.png
	- .eleventy.js
```

**Comment by aaronstezycki** [comment] 2022-10-09 16:55
Could be related, but I've experienced this using the new Vite Plugin, was just about to put an issue in over there, but perhaps this is to do with updates to the eleventy dev server.

**Comment by azangru** [comment] 2022-11-29 21:16
I think it's related to https://github.com/11ty/eleventy/issues/2491

**Comment by zachleat** [comment] 2022-11-29 21:35
Can you confirm if you’re using `--incremental` @sebthom?

**Comment by sebthom** [comment] 2022-11-30 09:51
@zachleat when I remove `--incremental` it works.

**Comment by zachleat** [comment] 2022-12-07 18:56
Duplicate of #2491, please subscribe over there! thanks y’all!

**Comment by zachleat** [comment] 2022-12-07 18:57
@aaronstezycki the vite issue is logged over at https://github.com/11ty/eleventy-plugin-vite/issues/13#issuecomment-1341242431

**Closed by zachleat** 2022-12-07 18:56 UTC
Labels: needs-triage
