### ISSUE TITLE
Better logging if rendering fails over plugin

### ISSUE THREAD

**Issue by Ryuno-Ki** [11ty/eleventy#599] opened 2019-07-07 10:19 UTC
After it annoyed me for a couple of day I set out to debug https://github.com/johanbrook/eleventy-plugin-reading-time/issues/1

It would have helped me, if eleventy were able to indicate, that a render problem is caused by a plugin.
Is that possible?

**Comment by zachleat** [comment] 2019-08-16 02:47
#646 is a duplicate of this but that one has a bit more info so we’ll coalesce over there—thank you!

**Closed by zachleat** 2019-08-16 02:47 UTC
Labels: enhancement
