### ISSUE TITLE
Global data object not updating if using a JavaScript Data File

### ISSUE THREAD

**Issue by navarrorc** [11ty/eleventy#341] opened 2018-12-13 04:38 UTC
Using Windows 10 with nodejs v11.4.0.

I'm experiencing and odd behavior where the global object that represents the JavaScript data file is not updating when I make changes to the source javascript file. I'm running `eleventy --serve`  and I have also tried `eleventy --watch`.

There's no issue if I use .json files, the global object updates as expected. The problem is only happening when using .js files that use `module.exports`

Here is an example of a .js file that does not update when I add more values to the array.

**users.js**
`module.exports = ["user1", "user2"];`

Please advise. Thank you.

**Comment by jevets** [comment] 2018-12-13 13:56
Tried it as a function?

```js
// users.js
module.exports = () => ([
  "user1",
  "user2",
])
```

**Comment by zachleat** [comment] 2018-12-13 14:38
Hm! We do some `require` cache busting to make sure that stuff updates properly. I made a reduced test case that seems to work fine with 0.6.0:

[eleventy-341-zip.zip](https://github.com/11ty/eleventy/files/2676423/eleventy-341-zip.zip)

**Comment by navarrorc** [comment] 2018-12-14 04:35
@zachleat I used `npx eleventy --serve` on your example project and it did not update the global object. I'm running Windows 10 and using nodejs v11.4.0.

**Comment by zachleat** [comment] 2018-12-14 05:44
A ha, Windows—thanks! Maybe related to #340 then!

**Comment by zachleat** [comment] 2019-10-31 01:57
This is almost certainly a duplicate of #596 (although that was opened later—the work happened there)

**Closed by zachleat** 2019-10-31 01:57 UTC
Labels: bug, bug-windows, duplicate
