### ISSUE TITLE
Eleventy doesn’t rerender shortcode when modifying imported shortcodes

### ISSUE THREAD

**Issue by dephiros** [11ty/eleventy#1052] opened 2020-03-27 00:46 UTC
**Is your feature request related to a problem? Please describe.**
When a shortcode is defined in an external files and being `require` into `.eleventy.js`, modifying the shortcode will not reload the site

Reproduce steps:
- Clone `https://github.com/dephiros/11ty-tailwind/` and checkout `11ty-require-reload`
- Do `yarn && yarn serve`
- Open the browser, notice `TEST` and `TEST REQUIRE`
- Open `.eleventy.js` and modify `Test` shortcode, notice the browser will reload with the new change
- Open `_11ty/Test.js` and change some text, notice the terminal is showing reload but the browser does not reflect the change

**Describe the solution you'd like**
Change in code that is `required` by `.eleventy.js` should reflect in the browser

**Describe alternatives you've considered**
I saw the issues mentioned in https://github.com/11ty/eleventy/issues/325 but it does not fix for me even with watch target. The shortcodes is still cached and require restarting the server

**Comment by chasemccoy** [comment] 2020-04-05 00:56
Also seeing this issue and spent waaayyyy too long trying to figure it out.

**Comment by chasemccoy** [comment] 2020-04-19 00:33
This is labelled as an enhancement, but I think it might be better considered a bug?

**Comment by dephiros** [comment] 2020-04-20 15:07
> This is labelled as an enhancement, but I think it might be better considered a bug?

I was thinking that after creating the ticket too but not sure how to change it

**Comment by chasemccoy** [comment] 2020-04-22 00:17
@zachleat could you help us get this labelled as a bug? (or give some guidance on whether it is a bug or expected behavior)

**Comment by reubenlillie** [comment] 2020-04-22 12:10
I cannot speak for @zachleat, but I've come to see this as "expected" behavior. It's akin to modifying the `.eleventy.js` file itself, which also requires an explicit call to rebuild/serve. If I'm not mistaken, it has more to do with how BrowserSync treats configuration files than it does with Eleventy proper.

**Comment by chasemccoy** [comment] 2020-04-22 15:27
@reubenlillie Hmm... I guess it seems different to me than modifying the `.eleventy.js` file because that file is purely for configuration, whereas shortcodes are actually producing markup (more like a template file in my eyes). I appreciate the context though! If this is expected behavior I can certainly work around it.

**Comment by reubenlillie** [comment] 2020-04-22 17:08
@chasemccoy, right. Even though shortcodes, filters, and so forth _can_ reside in separate modules that you pass `eleventyConfig`, ultimately, they are all registered via `.eleventy.js`. That's why those changes require the hard reload. Separate files or not, you're technically modifying the configuration either way.

**Comment by chasemccoy** [comment] 2020-04-22 17:58
That makes a lot of sense. Thanks @reubenlillie!

**Comment by jens-t** [comment] 2021-03-21 17:12
> It's akin to modifying the .eleventy.js file itself, which also requires an explicit call to rebuild/serve.

Actually, there is a config reset in watch mode, which is tirggered if `.eleventy.js` is modified (which was added in this commit: https://github.com/11ty/eleventy/commit/09973aecf48695b0e14d499b500bd9abd5015ac1).

I first thought, an easy workarround could be using the `beforeWatch` event (in combination with `addWatchtarget` if the additonal config files are not located inside the `_includes` directory) to trigger a change event on `.eleventy.js` if there is a change in these additonal config files, to trigger the built-in config reset. But this way the build would run twice, since there is no way to cancel the build from the `beforeWatch` event. So i ended up running my own chokidar instance for the files imported in `.eleventy.js` and trigger a change event on `.eleventy.js` from there. This feels very hacky, but still better than restarting the watch build on every change. :see_no_evil: 

So a built-in way could perhaps be, getting the import dependency graph of the `.eleventy.js` file and include these files in the watch mode reset config check. Or just provide an option like `addConfigResetTarget` to have the option to configure these files.

@zachleat What do you think? Are there any disadvantages in providing something like this? (I could send a PR, but wanted to double check first, since i saw your tweets about PR's :laughing: )

**Comment by zachleat** [comment] 2021-07-29 14:47
Sorry to chime in super late here, y’all. This is indeed a bug. The _goal_ is to not require re-starting the dev server (ever). But we have some work to get there, I think.

@jens-t Desired behavior would be that if a dependency of the config file changes it would reload the config, see https://www.11ty.dev/docs/watch-serve/#watch-javascript-dependencies I don’t think we need to add extra APIs here since we know the dependencies?

**Comment by jens-t** [comment] 2021-10-03 16:43
@zachleat The dependencies are not known for dynamic imports. Or maybe just not in my usecase?

I build an autoloader for my 11ty projects, so that all i have to do, is to create new files to add filter, shortcodes, transforms, tags and collections. This autoloader uses dynamic imports.

Example code for the autoloader:
```js
const initAutoload = conf => {
  const typeMapping = [
    {
      type: 'filter',
      extension: 'js',
      method: 'addFilter'
    },
    {
      type: 'tags',
      extension: 'js',
      method: 'addNunjucksTag'
    },
    {
      type: 'collections',
      extension: 'js',
      method: 'addCollection'
    },
    {
      type: 'shortcodes',
      extension: 'js',
      method: (name, content) => {
        if (!content.paired || content.paired !== true) {
          (!content.async || content.async !== true)
            ? conf.addNunjucksShortcode(name, content.shortcode)
            : conf.addNunjucksAsyncShortcode(name, content.shortcode);
        }
        else {
          (!content.async || content.async !== true)
            ? conf.addPairedNunjucksShortcode(name, content.shortcode)
            : conf.addPairedNunjucksAsyncShortcode(name, content.shortcode);
        }
      }
    },
    {
      type: 'transforms',
      extension: 'js',
      method: 'addTransform'
    }
  ];

  const initType = (data) => {
    const files = path.resolve(conf11ty.paths[data.type]) + '/**/*.' + data.extension;
    glob.sync(files).forEach(file => {
      const name = path.parse(file).name;
      const content = require(file);
      typeof data.method === 'function'
        ? data.method(name, content)
        : conf[data.method](name, content);
    });
  };

  typeMapping.forEach(type => initType(type));
};
```

**Comment by coryrylan** [comment] 2022-04-14 20:33
I think this is related. I import JS files from a separate directory to use in my `*.11ty.js` templates. Adding the files via `addWatchTarget` will trigger a reload but the import/required files are cached by node so the browser refreshes but the updates are not applied.

It looks like you can work around this by using the `decache` package and hook into the `eleventy.beforeWatch` event to remove it from the cache. This seems to allow me to edit the imported file and see the changes reflected in the browser without restarting the dev-server.

I use the esm package for esm use but this should work with require statements as well I think.

```javascript
// .eleventy.js
import decache from 'decache';

export default function (config) {
  config.addWatchTarget('../examples/**/*.js');

  config.on('eleventy.beforeWatch', async (files) => {
    files.forEach(file => decache(file));
  });

  ...
}
```

**Comment by zachleat** [comment] 2022-04-15 21:28
Circling back here, this might get fixed with #2147, shipped with `2.0.0-canary.5`.

Can anyone confirm or deny?

**Comment by zachleat** [comment] 2022-05-12 20:40
I can confirm the specific issue of modifying the dependency file is still present.

The first hurdle to cover here is that `.eleventyignore` has the `_11ty` folder, which them prevents files in that folder from being watched. I’ll fix that in upstream `eleventy-base-blog`.

As for the shortcode updates, stay tuned

**Comment by zachleat** [comment] 2022-05-12 21:29
The fix for this will ship with 2.0.0-canary.11

**Closed** 2022-05-12 21:28 UTC
Labels: bug, bug: --serve restart

**Comment by notacouch** [comment] 2024-03-26 17:20
Is anyone getting this issue in 11ty 3? I'm on alpha 5, I'm using JavaScript components in a nested `_src` directory, e.g. in `.eleventy.js`:

```javascript
import HeaderNav from './_src/components/global/HeaderNav.js';

export default function (eleventyConfig) {
  eleventyConfig.addShortcode('HeaderNav', function HeaderNavShortcode(currentPageUrl) {
    return new HeaderNav().render(currentPageUrl);
  });
}
```

Changes to HeaderNav trigger a refresh but the actual changes are not reflected unless I kill the server and start it up again. I should probably make a new issue for this if I can replicate.

**Comment by jens-struct** [comment] 2024-05-01 12:50
@notacouch Please see [here](https://github.com/11ty/eleventy/issues/3270) for a possible workaround.
