### ISSUE TITLE
Apply a default layout to multiple templates - not working?

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#933] opened 2020-02-14 13:47 UTC
**Describe the bug**
Following the docs here: https://www.11ty.dev/docs/data-template-dir/#example-apply-a-default-layout-to-multiple-templates

The layout does not seem to get applied.
The layout path is correct (it works from the frontmatter)

**To Reproduce**
All my content is in a `_content` directory. The `_layout` directory is adjacent to it.

`_content.json`
```json
{ "layout": "../_layouts/main.njk" } 
```

Repo here: https://github.com/StarfallProjects/11tyDocsSkeleton

**Expected behavior**
The `main.njk` layout should be applied to every file in `_content`.

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux] - Windows 10, Node 12.15.0
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`] - 0.10.0

**Other info**
I had a similar issue with data files + layout files (a layout didn't seem to be able to pick up the data when it was in the same folder, but did when I moved it to `_data`)

**Comment by StarfallProjects** [comment] 2020-02-14 19:46
I went back and tried with `_content.11tydata.json` (not how it is in the docs, but how it was on the Twitch stream a while ago) but still no luck. It doesn't seem to even be looking for the layout - no error messages.

**Comment by scottishstoater** [comment] 2020-02-14 22:45
Hey @StarfallProjects, hopefully I can help you.

In your `.eleventy.js` file you currently have (lines 17-20):

```js
dir: {
  input: "_content",
  includes:"../_includes",
  layouts:"../_layouts",
  data:"../_data"
},
```

Your `_data`,  `_layouts` and `_includes` folder look as though they are looking in a directory up from where they actually live. 

Can you try removing the `../` from them so it reads.


```js
dir: {
  input: "_content",
  includes:"_includes",
  layouts:"_layouts",
  data:"_data"
},
```

Lastly, in your `_content.json` file you don't need to traverse to the file as you have told Eleventy in your `.eleventy.js` file where to look. Your `_content.json` file should look like this:

```js
{ 
    "layout": "main.njk"
} 
```

Could you try that an let us know how you get on?

**Comment by pdehaan** [comment] 2020-02-15 00:41
Not sure if this might be related to https://github.com/11ty/eleventy/issues/935 (recently fixed in GitHub, but not yet released on npm).

I was able to get the site working (and have it inherit layouts) by installing Eleventy directly from GitHub instead of the hosted npm version, but I also moved a bunch of files into the `input` \_content/ directory, which might have fixed a couple relative pathing issues:

```sh
$ tree _content

_content/
├── _content.json
├── _data/
│   ├── environment.js
│   └── nav.js
├── _layouts/
│   ├── main.njk
│   └── nav.njk
├── _snippets/
│   └── imasnippet.md
├── about.md
├── features/
│   ├── conditional-output.md
│   ├── content-reuse.md
│   ├── index.md
│   ├── navigation.md
│   └── project-structure.md
└── index.md

4 directories, 13 files
```

**Comment by StarfallProjects** [comment] 2020-02-15 11:45
@scottishstoater I found I had to put the paths like that in `.eleventy.js` because I'd put `_content` as the input directory. If I don't have the `../`, it seems to look for e.g. `_layouts` inside the `_content` directory. 
Data files in my `_data` folder are working. It's just the data files for single templates (e.g. `myBlogPost.11tydata.js`) and directories (e.g. `_content.json`) that aren't.

@pdehaan I tried moving everything inside `_content` but that alone didn't seem to work. It looks like that issue you linked may solve it though - will give that a try.

Moving everything into `_content` also threw up a new issue - when I set the layout in the frontmater of `index.md`, it found it ok in `_layouts`, but then couldn't find `nav.njk` until I did:
````
{% include "_content/_layouts/nav.njk" %}
```
This seems odd - I'd have expected it to either look from `_content`, which is effectively the root (input) or a relative path (and they're in the same folder, so nav.njk should have done it)

**Comment by pdehaan** [comment] 2020-02-15 20:44
@StarfallProjects I tried pushing a PR at https://github.com/StarfallProjects/11tyDocsSkeleton/pull/1 which I tried my best to document w/ review comments.

**Comment by StarfallProjects** [comment] 2020-02-21 21:11
Thanks @pdehaan , I really appreciate the feedback, and it's given some insight into 11ty. I was quite keen to keep the folder structure, and I definitely don't want to set the layout individually, so will hold out for the update. Your comments were very helpful though.

**Comment by zachleat** [comment] 2020-02-24 13:45
Sounds like a duplicate of #935 but we’ll leave this open until we’re sure.

**Comment by zachleat** [comment] 2024-04-09 17:03
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Closed by zachleat** 2024-04-09 17:03 UTC
Labels: duplicate
