### ISSUE TITLE
Add documentation info for JS Template Literals

### ISSUE THREAD

**Issue by JonathanTroyer** [11ty/eleventy#306] opened 2018-11-16 01:32 UTC
I've successfully configured eleventy with simple input/output folders and can render things just fine. However, whenever I add a `.jslt` file it simply fails with "Having trouble rendering template ". Unfortunately, the current documentation gives no indication as to how to properly use template literals. I've tried `return literal`, `module.exports = literal`, just having the plain literal in a file, etc. I've even tried something as simple as ``<h1>Stuff</h1>``, but that fails with ``Having trouble rendering template ./src/test.jstl: '`<h1>Stuff</h1>`'``.

I'd greatly appreciate any kind of direction or help here, as I'd love to be able to use template literals.

**Comment by kleinfreund** [comment] 2018-11-16 10:13
What do you want to use JS template literals for? As far as I know, Eleventy knows nothing about a JSTL extension. Are you talking about using template literals for template files?

**Comment by jevets** [comment] 2018-11-16 14:45
Docs do mention it https://www.11ty.io/docs/languages/jstl/ 

I hadn't used them yet, but I just did a quick test and also getting the rendering error

**Comment by jevets** [comment] 2018-11-16 15:15
With debug mode on, I'm just getting an error about `Could not stringify data` / `Converting circular structure to JSON (TypeError)` on the simplest test.

@zachleat I think we've got a bug

**Comment by kleinfreund** [comment] 2018-11-16 16:09
Oooooohhhh.

**Comment by jevets** [comment] 2018-11-16 17:19
I messed around with the engine a little bit, but comparing to master, looks like Zach has already made some changes to it. Quite possible this may be fixed in next release (I don't know though)

https://github.com/11ty/eleventy/blob/3367e8e5e22ced9989322247d0057e9fd11eacc1/src/Engines/JavaScriptTemplateLiteral.js

**Comment by zachleat** [comment] 2018-11-18 19:12
See also #263

**Comment by zachleat** [comment] 2018-11-18 19:14
See also #118

**Comment by zachleat** [comment] 2018-11-21 14:40
To clarify my previous comments: The problems you’re having are caused by an active issue, yes. So this is almost certainly a duplicate of #263. Look for the fix in 0.6.0.

Also follow along at #118, which will allow us to do powerful things like named literals, etc etc.

**Closed by zachleat** 2018-11-21 14:40 UTC
Labels: bug
