### ISSUE TITLE
Can't create collections that don't render to a page at _site

### ISSUE THREAD

**Issue by guayom** [11ty/eleventy#150] opened 2018-06-25 18:18 UTC
Hi! I love Eleventy. It's an amazing tool. This is a feature request and maybe a bug report.

I'm building a site using Netlify CMS. In the CMS I would like to have a section called "Features". I want to have an instance for each feature, meaning, each feature should have it's own .md file. 

So I created a `_features` directory and put all my .md files in there. I set a "features" tag to all files to be able to use them as a collection, and then list all features on my home page. 

All of this works perfectly. BUT, it also outputs `_site/_features/feature1/index.html`, `_site/_features/feature2/index.html`, and so on. I don't want those pages. Actually, the homepage is the only page that I want to be outputted to `_site`.

I tried a couple things that didn't work:
1. Setting `permalink:null` to all files.
2. Setting `permalink: ""` to all files.
3. Adding `_features` to my `.eleventyignore` But of course that doesn't work for me because I do want eleventy to use the data contained in those files.

### What happens
Files in `_features/` are being outputted to `_site/_features`

### What I would expect 
Be able to configure eleventy in a way that files in `_features/` are **not** outputted to  `_site/`. I didn't find it in the docs. (Did I miss it?).

**OR**

I guess that this could also be solved by being able to have a `_data/features` directory and that all .json files in there could be used as a collection. So the data in `_data/features/feature1.json`, `_data/features/feature2.json` would be available at `collections.features`.

### Bug ?
When I set the permalink to an empty string, the permalink is ignored completely. But I don't know if that is by design or a bug.

**Comment by chrisdmacrae** [comment] 2018-06-25 18:40
I've done this before but can confirm it no longer works.

It may be better for this feature to be more explicit because of certain implications. Hugo, for example, lets you mark a file as `output: false` and this removes the file from the main page indexes, etc, as to prevent plugins and such from mucking them up.

**Comment by zachleat** [comment] 2018-06-26 19:14
If I’m reading this correctly, this seems to be a duplicate of #61 right?

Can you upvote over there?

**Comment by guayom** [comment] 2018-06-26 19:22
Yeah, you're right. I'll go vote. Thanks!

**Comment by zachleat** [comment] 2018-06-26 21:58
Thank you!

**Closed by zachleat** 2018-06-26 21:58 UTC
Labels: duplicate
