### ISSUE TITLE
Possible bug in addPassthroughCopy, but maybe a doc issue

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#2461] opened 2022-06-29 17:37 UTC
**Describe the bug**

I'm not sure if this is a bug, as it seems new, but it may also be a doc issue. I built an incredibly simple site:

/index.liquid
/random.jpg
/.eleventy.js

My .eleventy.js was:

```js
module.exports = function(eleventyConfig) {

	eleventyConfig.addPassthroughCopy("**/*.jpg");

};
```

I was doing this to test something else. When I ran this, it worked just fine, copying the result to /_site. 

However, if I ran it a second time, I got:

```
[11ty] Error with passthrough copy: (more in DEBUG output)
[11ty] 1. Having trouble copying './**/*.jpg' (via TemplatePassthroughManagerCopyError)
[11ty] 2. Error copying passthrough files: ENOENT: no such file or directory, open '_site/Cobra-Commander.jpg' (via TemplatePassthroughError)
[11ty] 3. ENOENT: no such file or directory, open '_site/Cobra-Commander.jpg' (via Error)
```

I noticed that my _site folder now also had a _site folder:

![image](https://user-images.githubusercontent.com/393660/176500219-ad8763c1-881e-4216-ac01-f08b72567e0a.png)

It's almost like the glob is picking up stuff in _site, which... I mean I guess the glob would match stuff there, but I feel like in the past Eleventy didn't have this issue. I also assume if I were using directories like so:

/_site
/src
/.eleventy.js

Where I told Eleventy to use src as the input folder, it wouldn't have this same issue. 

So... is this a bug, or is it expected, and if expected, maybe the docs for addPassthroughCopy should use a 'safer' glob as an example?

- Eleventy Version: 1.0.1

**Comment by zachleat** [comment] 2022-06-30 19:37
Yeah, probably just missing a `.gitignore` file? Though honestly my perspective on the reliance on `.gitignore` here may be shifting a bit after reading through #857 again.

**Comment by zachleat** [comment] 2022-06-30 22:15
Just diving in a little bit deeper here I think the confusion is probably that globs passed to `addPassthroughCopy` bypass ignores!

Here are the fast-glob that bypass ignores worth looking into here:
* https://github.com/11ty/eleventy/blob/8674f34600852fa2d1305deb012420d984a691f8/src/TemplatePassthrough.js#L110
* https://github.com/11ty/eleventy/blob/8674f34600852fa2d1305deb012420d984a691f8/src/TemplateData.js#L231
* https://github.com/11ty/eleventy/blob/8674f34600852fa2d1305deb012420d984a691f8/src/Engines/TemplateEngine.js#L122

**Comment by SuaYoo** [comment] 2022-09-06 15:04
Ran into this, too, I bypassed this by ignoring `_site` in the glob pattern.
```js
eleventyConfig.addPassthroughCopy("{,!(_site)/**/}*.jpg");
```

**Comment by zachleat** [comment] 2022-11-18 18:54
Going to coalesce over at #1134 which is a duplicate of this one—please subscribe over there!

**Closed by zachleat** 2022-11-18 18:54 UTC
Labels: documentation, education, feature: 🪞 ignores
