### ISSUE TITLE
rejectattr and selectattr only on boolean properties?

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#910] opened 2020-02-06 22:39 UTC
The docs only show examples where these test a boolean property.
Can they test object properties that are not boolean?
For example, if the objects in an array have a `size` property, can I get only the objects where `size` is greater than 5?

**Comment by Miosame** [comment] 2020-06-09 18:44
As confirmed by: https://jbmoelker.github.io/jinja-compat-tests/filters/rejectattr/ and: https://mozilla.github.io/nunjucks/templating.html#rejectattr-only-the-single-argument-form sadly it is single argument only, it does not e.g. support `rejectattr('url', 'equalto', page.url)`

**Comment by binyamin** [comment] 2022-03-10 22:24
Thanks @Miosame , closing

**Closed by binyamin** 2022-03-10 22:24 UTC
Labels: education

**Comment by goulvench** [comment] 2023-03-30 12:28
Hi, do you have a *working* custom filter example? I'm new to both e11y and nunjucks and I'm having a hard time figuring it out. I've tried implementing a custom filter but it seems `select` doesn't pick it up.

Here's what I've done for the moment:

```js
// .eleventy.js
module.exports = function (eleventyConfig) {
  // beginning of config…
  eleventyConfig.addFilter("user_id", function(el) {
    return el.user_id;
  });
  // …end of config
}
```

```js
// index.njk template
{% set collection = [{user_id: 1, name: "one"}, {user_id: 2, name: "two"}] %}
{{ collection | select("user_id", 1) }}
```

And here's the crash log:
```shell
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./pages/index.njk (via TemplateContentRenderError)
[11ty] 2. (./pages/index.njk)
[11ty]   Error: test not found: user_id (via Template render error)
[11ty] 
[11ty] Original error stack trace: Template render error: (./pages/index.njk)
[11ty]   Error: test not found: user_id
[11ty]     at Object._prettifyError (~/Sites/site/node_modules/nunjucks/src/lib.js:36:11)
[11ty]     at ~/Sites/site/node_modules/nunjucks/src/environment.js:563:19
[11ty]     at Template.root [as rootRenderFunc] (eval at _compile (~/Sites/site/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:111:3)
[11ty]     at Template.render (~/Sites/site/node_modules/nunjucks/src/environment.js:552:10)
[11ty]     at ~/Sites/site/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:416:14
[11ty]     at new Promise (<anonymous>)
[11ty]     at ~/Sites/site/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:415:14
[11ty]     at Template._render (~/Sites/site/node_modules/@11ty/eleventy/src/TemplateContent.js:473:28)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async TemplateMap.populateContentDataInMap (~/Sites/site/node_modules/@11ty/eleventy/src/TemplateMap.js:494:13)
```

**Comment by pdehaan** [comment] 2023-03-30 15:37
@goulvench I'd probably use a custom filter:

```js
eleventyConfig.addFilter("find", function (arr=[], key="", value) {
  return arr?.find(item => item[key] === value);
});
```

### USAGE
```njk
{% set collection = [{user_id: 1, name: "one"}, {user_id: 2, name: "two"}] %}
{{ collection | find("user_id", 1) | dump }}
```

### OUTPUT
```json
{"user_id":1,"name":"one"}
```

And if you pass in an invalid `user_id` (ie: `3`) it will just return a falsy `undefined`.

PS: probably best to open a new [Discussion](https://github.com/11ty/eleventy/discussions) if you have further questions since I'm not sure how many people are tracking old issues.

**Comment by goulvench** [comment] 2023-04-07 09:06
Thanks a lot @pdehaan! That works. I had to change `find` with `filter` because I need to return all matches, but otherwise that works fine. It would have been much easier if `selectattr` supported a second argument to filter by value though.
