### ISSUE TITLE
Should `eleventy --version` process any files or just output the version to console?

### ISSUE THREAD

**Issue by tannerdolby** [11ty/eleventy#1792] opened 2021-05-24 07:02 UTC
**Describe the bug**
When I run `eleventy --version`, it seems that my global data file [github.js](https://github.com/tannerdolby/tannerdolby.com/blob/master/src/_data/github.js) is executing. I guess it is an anonymous async function being exported for use but I didn't expect `eleventy --version` to process any files.

```
tannerdolby:11ty-portfolio TannerDolby$ eleventy --version
(node:21199) ExperimentalWarning: The fs.promises API is experimental
Caching: https://api.github.com/repos/tannerdolby/eleventy-photo-gallery
Caching: https://api.github.com/repos/tannerdolby/eleventy-plugin-metagen
Caching: https://api.github.com/repos/tannerdolby/eleventy-plugin-sharp-respimg
Caching: https://api.github.com/repos/tannerdolby/what-to-watch
0.11.1
```

**To Reproduce**

1. Check version with `eleventy --version`
2. See console output from code being run in a global data file

**Expected behavior**
I expected `eleventy --version` to not run any code or process files but simply to log the version number to the console.

**Screenshots**
<img width="590" alt="Screen Shot 2021-05-24 at 12 01 13 AM" src="https://user-images.githubusercontent.com/48612525/119309464-31c7ff80-bc23-11eb-975f-ca95fe43fa0d.png">

**Environment:**

- OS and Version: [MacOS High Sierra v10.13.6]
- Eleventy Version [v0.11.1]

**Comment by pdehaan** [comment] 2021-05-25 07:34
Possibly a dupe of #1313

**Comment by tannerdolby** [comment] 2021-05-25 09:19
@pdehaan Yeah it seems like possible dupe where `eleventy --version` is running a build. I had a look at [your comment](https://github.com/11ty/eleventy/issues/1313#issuecomment-657124349) in that issue and saw:

> I wonder if explicitly checking for --version and --help and aborting early would speed things up. .... to see if the expensive part is the `elev.init()` call on L64 which is possibly unneeded for reporting a version or help string (or maybe not, what do I know)

I think you might be onto something here. It looks like the `elev.init()` call is whats running a build or processing files (not entirely sure what is being "initialized"). If we could just log the `version` or `help` console output without running `elev.init()` like you mentioned that should do it, I think.

**Comment by zachleat** [comment] 2021-06-15 12:37
Yeah let’s move to #1313 for this one! It’s the same issue I think. Thanks for the report!

**Closed by zachleat** 2021-06-15 12:37 UTC
Labels: bug

**Comment by tannerdolby** [comment] 2021-06-15 14:42
> Yeah let’s move to #1313 for this one! It’s the same issue I think. Thanks for the report!

Your welcome! It looks like your commit fixes things. Nice work @zachleat !
