### ISSUE TITLE
11tydata root config

### ISSUE THREAD

**Issue by ValeriyDyachenko** [11ty/eleventy#590] opened 2019-06-27 17:20 UTC
My project is based on a hierarchy of folders, depending on the nesting level, a specific template and data are used.

I use 11tydata.js files in directories, but this is not convenient. It would be nice to add the ability to set the binding of 11tydata data in the configuration file, for example:

config.11tydata.js:
```js
const someData = {}
const someData2 = {}

const dirTempales = {
     'myFolder/': {
        data: someData,
        name: 'index.11tydata.js',
     },
     'myFolder/(.*)/': {
        data: someData2,
        name: `$1.11tydata.js`,
    },
}

return dirTempales;
```

**Comment by zachleat** [comment] 2019-07-01 02:41
I believe this is a duplicate of https://github.com/11ty/eleventy/issues/245 or maybe #184. Can you confirm?

**Comment by zachleat** [comment] 2019-07-16 12:35
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-07-16 12:35 UTC
Labels: duplicate, waiting-to-close
