### ISSUE TITLE
Consider upgrading base version of LiquidJS in 11ty standard package

### ISSUE THREAD

**Issue by danfascia** [11ty/eleventy#1545] opened 2020-12-07 22:05 UTC
I know that I can upgrade my LiquidJS node_module and import a new version of the Liquid rendering engine myself - which I do so that I can access some of the great features of the Liquid language (such as the `where` filter).

I'm wondering why the LiquidJS version included in 11ty is stuck back on version 6.4.3 and @zachleat would consider upgrading by default to the latest stable library version in the next 11ty version?

**Comment by Ryuno-Ki** [comment] 2020-12-07 22:20
`master` is already on v9 (I see, https://github.com/11ty/eleventy/commit/a37a5c675d97268dab50e83e4692e152be9fbf0d from September 2020 for example).

Will be released with v1, I guess.

**Comment by danfascia** [comment] 2020-12-07 22:34
Ohhh... then I have a glitch in the works! Must be a hardcoded version somewhere in a package which I need to change to @latest

Good to see this because Liquid seems to have the best filters as well as being faster than NJK on benchmarks

**Comment by zachleat** [comment] 2020-12-07 23:45
I believe this is a dupe of #469 and #1058, both on https://github.com/orgs/11ty/projects/5

**Closed by zachleat** 2020-12-07 23:45 UTC
Labels: enhancement

**Comment by Ryuno-Ki** [comment] 2020-12-08 15:33
Ah, those are the issue / PR I was looking for!

**Comment by danfascia** [comment] 2020-12-08 16:38
OK actually I'm back again because something really strange is going on.

From a completely fresh install where all that I do is `npm install @11ty/eleventy` the liquidjs module it pulls down is 6.4.3

Why is it reverting to this old outdated dependency version?

**Comment by Ryuno-Ki** [comment] 2020-12-08 18:35
Because v1 is not published yet. You can install from a branch instead: `npm i @11ty/elventy#master` should pull directly from the `master` branch (as long as it wasn't renamed to `main`).

Be aware, that it is bleeding edge!

**Comment by binyamin** [comment] 2020-12-11 12:21
You can also use `npm i github:11ty/eleventy`, without specifying the branch name.
