### ISSUE TITLE
11ty don't recognize multiline shortcode LiquidJS

### ISSUE THREAD

**Issue by shkarinn** [11ty/eleventy#3325] opened 2024-06-18 13:45 UTC
### Operating system

Windows 11

### Eleventy

3.0.0-alpha.13

### Describe the bug

11ty does not recognize multiple lines shortcodes, separated by comma. 11ty only processes shortcodes that are written in a single line.

### Reproduction steps

1. Define multiple-line custom shortcodes with 4 prop's separate by commas.
2. Separate it to 4 lines
3. Attempt to build the project using 11ty.
4. Observe that 11ty does not recognize the multiline shortcodes properly.

### Expected behavior

Shortcodes should be recognized and processed correctly by 11ty, even when specified in multiple lines.

### Screenshots

![image](https://github.com/11ty/eleventy/assets/29929365/90e052f6-348b-462e-9e75-7052bcf38089)
![image](https://github.com/11ty/eleventy/assets/29929365/73ea0dd1-3d42-48c3-9f2c-964297b704bf)
![image](https://github.com/11ty/eleventy/assets/29929365/641677b0-4e89-4066-8228-23829a7c3ba7)

**Comment by zachleat** [comment] 2024-06-18 18:43
Duplicate of #2679. Please follow along over there!

**Closed by zachleat** 2024-06-18 18:43 UTC
Labels: needs-triage, template language: liquid
