### ISSUE TITLE
Hot reload is only working for files in the root directory (WSL)

### ISSUE THREAD

**Issue by GPAlzate** [11ty/eleventy#3321] opened 2024-06-12 19:41 UTC
### Operating system

Windows 11

### Eleventy

2.0.1

### Describe the bug

Hi, I'm trying to figure out why hot reload isn't working for any file that isn't directly in the root? I tried manually setting the `eleventyConfig.serverOptions.watch` field (as described in the [dev-server docs](https://www.11ty.dev/docs/dev-server/)), as well as the `eleventyConfig.addWatch` field (as described in the [watch-serve ](https://www.11ty.dev/docs/watch-serve/) docs.

Here's an example of my .eleventy.config file:
```
    // eleventy-dev-server options
    eleventyConfig.setServerOptions({
        watch: ["src/**/*.html", "_site/**/*.html"]
    });
```

### Reproduction steps

1. Run `npx @11ty/eleventy --serve
2. Edit `src/index.html`, for example (any other file that isn't in root will have this same issue), and save
3. Hot reload doesn't happen
4. Edit and save any other file in the root directory (e.g. package.json) - hot reload happens.

### Expected behavior

The local server should hot reload when editing files in the input `src` directory.

### Reproduction URL

https://github.com/GPAlzate/gpalzate.github.io

**Comment by GPAlzate** [comment] 2024-06-12 20:14
Found a fix here: https://github.com/11ty/eleventy/issues/701
If you are on WSL2, your directory should be in ~. My directory was in /mnt since it was on the desktop, which won't work.

**Comment by zachleat** [comment] 2024-06-18 19:57
Thanks for reporting back! Looks like this is a duplicate of #701.

I added an additional note to the Watch and Serve docs about this issue specifically. You can workaround it by moving your project directory under `~` or using the polling feature of chokidar, example here: https://www.11ty.dev/docs/watch-serve/#advanced-chokidar-configuration

**Closed** 2024-06-18 20:00 UTC
Labels: bug: windows, education, bug-has-workaround
