### ISSUE TITLE
Hot reload (--serve) not working when input directory is specified in the .eleventy.js file  

### ISSUE THREAD

**Issue by FilipSzutkowski** [11ty/eleventy#1501] opened 2020-11-06 16:27 UTC
When creating a simple Eleventy project with an _index.md_, the hot reload works on every change I make to it after running `npx @11ty/eleventy`. The problem starts when specifying input directory in _.eleventy.js_. After inserting the code below inside _.eleventy.js_, moving the _index.md_ to the input directory, and running `npx @11ty/eleventy` the hot reload doesn't detect any changes in neither the index file or even _.eleventy.js_.
```
//.eleventy.js
module.exports = eleventyConfig => {
    return {
        dir: {
            input: "input"
        }
    }
    
};
``` 
**To Reproduce**

1. Make a project dir and run `npm init -y`
2. Install 11ty locally `npm install --save-dev @11ty/eleventy`
3. Create an _index.md_ file inside "input" directory
4. Create _.eleventy.js_ with the code above
5. Run with `npx @11ty/eleventy --serve`
6. Make changes to the contents of _index.md_

**Expected behavior**
Expected to work the same way as without specifying the input directory. 

**Video of the issue**
[Youtube](https://youtu.be/iIUnjCJVQCE) - I present the issue in this video. I'm first showing the index hot reload working normally when in main project directory, and then not working again when moving it to another directory while specifying it in the _eleventy.js_

**Environment:**

- Windows 10 with WSL 2 (Ubuntu 20.04.1 LTS (Focal Fosa))
- Eleventy version: 0.11.1

**Additional context**
The issue is still present when working on a project with a present body element with many templates in place. I am following a JAMstack course on LinkedIn learning, and the guy in the course has no problems with the hot reloads feature when the input directory is specified.

**Comment by jeremy-immersitech** [comment] 2022-03-05 00:13
I'm no longer seeing this with eleventy version 1.0.0

**Comment by zachleat** [comment] 2024-06-18 20:04
Duplicate of #701.

You can workaround it by moving your project directory under `~` or using the polling feature of chokidar, example here: https://www.11ty.dev/docs/watch-serve/#advanced-chokidar-configuration

**Closed by zachleat** 2024-06-18 20:04 UTC
Labels: bug: windows, education
