### ISSUE TITLE
Incremental build for markdown files

### ISSUE THREAD

**Issue by magua-io** [11ty/eleventy#2021] opened 2021-10-12 20:22 UTC
**Is your feature request related to a problem? Please describe.**
Minor modification on a single markdown file takes the whole build time to reload. The more pages I have, the longer it takes.

**Describe the solution you'd like**
Incremental build support for markdown files. Fast reloading should happen after saving the markdown file.

**Describe alternatives you've considered**
N/A

**Additional context**
I have two repos are using Eleventy as the SSG to generate documentation pages. The first one contains around 20 pages, and each rebuild time is around 25 seconds. The second one contains 180+ markdown files, and each rebuild time is around 160 seconds.

**Comment by zachleat** [comment] 2021-10-16 19:40
Duplicate of #108 and #2022

**Closed by zachleat** 2021-10-16 19:40 UTC
Labels: enhancement
