### ISSUE TITLE
Permalinks for images

### ISSUE THREAD

**Issue by igr** [11ty/eleventy#456] opened 2019-03-19 20:13 UTC
Let's say I have a folder `posts`. Each post has a subfolder with `index.md` and a few images used on a page (passthrough is turned on for images extension).

```
/posts
  /first-post
    index.md
    foo.jpg
```

This structure is rendered to e.g. `out/posts/...`. Everything works as expected.

If I want to change permalink for all posts (using `/posts/posts.json`), it will affect only the output of `md` files - but images will be copied in old folders.

How can I change the permalinks for the images, too?

I do not want to split images in separate folders, as they logically belong next to a page and I can write my article in visual markdown editor where I can preview the image. So the article and the image(s) should stay together.

**Comment by zachleat** [comment] 2019-03-22 02:06
Hmm, is this a duplicate of #379? Looks like you commented over there too

Perhaps also tangentially related to #237.

**Comment by igr** [comment] 2019-03-22 05:37
@zachleat true, #379 seems similar.

in Hugo, for example, you have a concept of a _bundle_ where everything that is in the same folder as index.md is considered as part of that page. I like this concept as the logical place where to put e.g. images etc is next to the MD file.

Maybe you can simply add a flag `bundle: true` that indicates that the whole folder is just a _page_ :)

**Comment by zachleat** [comment] 2019-03-23 01:41
Let’s coalesce over at #379 if that’s okay with you!

**Closed by zachleat** 2019-03-23 01:41 UTC
Labels: duplicate
