### ISSUE TITLE
Can't get access to data inside liquid file which is triggered by the 'render'

### ISSUE THREAD

**Issue by shkarinn** [11ty/eleventy#3172] opened 2024-01-22 12:28 UTC
### Operating system

Windows 11

### Eleventy

2.0.1

### Describe the bug

Hello.
I can't get access to data inside liquid file which is triggered by the 'render'. But depricated tag 'include' get access to data.
If I use old tag include
{% include 'header/section' %}
my data inside include file is working

For example I can get all data from 11ty global inside header/section.liquid file
{{ collections.all[0].template.templateData.globalData | debug }}

But if use new tag
{% render 'header/section' %}
I got undefined <pre>undefined</pre>

I can get access to data only outside file section.liquid
{% render 'header/section' for contact.buttons as item %}

liquid have section tag, but js version not.
liquidjs have only render, include, layout tags.
But include is Deprecated and working good.
Render tag have problem.
Maybe this problem inside 11ty...

### Reproduction steps

4. See an error

**Comment by vrugtehagel** [comment] 2024-02-21 09:56
Possibly a duplicate of https://github.com/11ty/eleventy/issues/2453

**Closed** 2024-04-10 21:14 UTC
Labels: needs-triage
