### ISSUE TITLE
.eleventyignore doesn't support negative patterns

### ISSUE THREAD

**Issue by veleek** [11ty/eleventy#693] opened 2019-09-14 06:41 UTC
**Describe the bug**
`.eleventyignore` files that use negative ignore patterns return unexpected results because eleventy modifies the paths a bit.

**To Reproduce**
1. Create an eleventy ignore file with a regular pattern and a negative pattern
    ```
    site/**/*
    !site/events/2018/**
    ```
2. Run eleventy ignore
3. Note that no files are copied

**Expected behavior**
Negative patterns should allow you to re-include ignored paths

**Environment:**
 - OS and Version: Windows
 - Eleventy Version: 0.9.0

**Additional context**
Eleventy modifies the patterns in the ignore file by prefixing a relative path header (`./`) and then adding the `!` to the beginning.  As a result, the example above (`!site/events/2018/**`) gets turned into `!./!site/events/2018/**` when being passed to fast-glob.  Fast glob processes negative patterns separately so it pulls that pattern out and removes the ! and actually strips the ./ before using it, so it ends up using `!site/events/2018/**` as the negative pattern and this basically says ignore anything that's not a match for `site/events/2018`.  Since `site/events` is not a match for this, the whole folder gets excluded and fast-glob never scans any deeper for files that SHOULD be included.

I haven't had a chance to try it out yet, but this problem could potentially be solve by not modifying the patterns in `.eleventyignore` and using the new `ignore` parameter to fast-glob which handles the negation for you.  I haven't looked too closely at what modifications eleventy does to see if they're necessary for some of the output processing so hopefully it's just not necessary.

Note: This is a new issue related to the upgrade to fast-glob 3.X.  Definitely prefer to use the new version, but would love to have it continue to use .eleventyignore the same way I was before.

**Comment by ogdenstudios** [comment] 2019-09-18 17:04
I think this is a duplicate of #677

**Comment by veleek** [comment] 2019-09-19 03:21
Yeah.  Pretty much a duplicate.  If you don't have an .eleventyignore file it will use the gitignore by default.  But that explains why my searches for existing bugs didn't find anything.

**Closed** 2019-11-28 04:17 UTC
Labels: bug

**Comment by zachleat** [comment] 2019-11-28 04:27
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment] 2019-11-28 04:28
Placing this into the enhancement queue. #677 is a related issue to this but not quite the same.

As info, v0.10.0 will include a debug warning if it encounters one of these entries.

**Comment by alberto** [comment] 2020-05-23 06:44
I was hit by this. My use case is I use Sass so I want to `.gitignore` the CSS files output directory. But I still want eleventy to process them. I tried using a negative pattern in `.eleventyignore` to include them but it didn't work.

In case it helps, `eslint` does something similar with `.gitignore` and `.eslintignore` and it uses https://github.com/kaelzhang/node-ignore to achieve this behaviour.

**Comment by zachleat** [comment] 2021-03-24 14:22
A note for future me:

Two dependencies require some level of support here: `chokidar` and `fast-glob`

In 1.0 we’ll use fast-glob’s `ignore` option instead of negated globs. We were already using chokidar’s `ignored` option here.

These will both need to be tested to know if negated patterns are supported in those features.

**Comment by zachleat** [comment] 2025-11-07 21:08
Related #3680, #3442
