### ISSUE TITLE
Client-side JS causing ReferenceError with `eleventy --serve`

### ISSUE THREAD

**Issue by c-bec-k** [11ty/eleventy#1088] opened 2020-04-11 16:55 UTC
**Describe the bug**
I have a page that loads client-side JS and, when I use the `--serve` parameter I'm getting the following error:

```
Writing _site/cast/index.html from ./_src/cast.11ty.js.
Writing _site/index.html from ./_src/index.11ty.js.
Copied 6 items / Wrote 2 files in 0.21 seconds (v0.10.0)
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> document is not defined

`ReferenceError` was thrown:
    ReferenceError: document is not defined
        at Object.<anonymous> (/Users/christopher/Documents/Git/TabletopGalaxy/_src/scripts/ca
stCrew.js:1:14)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
        at Module.load (internal/modules/cjs/loader.js:1002:32)
        at Function.Module._load (internal/modules/cjs/loader.js:901:14)
        at Module.require (internal/modules/cjs/loader.js:1044:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at getDependenciesFor (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/@11ty/d
ependency-tree/main.js:21:5)
        at getCleanDependencyListFor (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/
@11ty/dependency-tree/main.js:73:22)
        at /usr/local/lib/node_modules/@11ty/eleventy/src/EleventyWatchTargets.js:95:9
```

The `document`in question  (from line 1 of `castCrew.js`)
```js
const tabs = document.querySelector('.tabs');
```

And my `.eleventy.js` is:
```js
module.exports = {
  passthroughCopy: '_src/scripts',
  dir: {
    data: "_data",
    input: "_src",
    layouts: "../_layouts"
  },
  dataTemplateEngine: "11ty.js",
  templateFormats: ['11ty.js', 'css', 'svg', 'jpg', 'png', 'js'],
}
```

**To Reproduce**

1. Create a new 11ty project
2. Use `.11ty.js` as the template
3. Create a subdirectory for the source files
4. Create a page that links a JS file
1. Create the linked JS file in the source subdirectory
1. Enter the command `eleventy --serve`
1. Encounter the error

**Expected behavior**
The expected behaviour is that no error should occur. The JavaScript file should be passed through to the `_site` folder and not be parsed.

**Environment:**

- macOS Cataline 10.15.4
- Eleventy Version: 0.10.0

**Comment by Ryuno-Ki** [comment] 2020-04-11 17:28
Originally asked [on Twitter](https://twitter.com/c__beck/status/1248694925966880771).

**Comment by jeremiahlee** [comment] 2020-04-12 13:05
I'm also having this issue. I have some static JavaScript I just want to be passed through, but adding JS files via `eleventyConfig.addPassthroughCopy()` or to `templateFormats` results in `ReferenceError: document is not defined`.

**Comment by carlos-ds** [comment] 2020-04-13 15:19
If you remove "js" from the templateFormats array in .eleventy.js, everything should work as you expect. Eleventy will your copy .js files over by default so there's no need to add it there. This is not specifically mentioned in the docs on https://www.11ty.dev/docs/copy/ , perhaps that is something to be looked into.

**Comment by c-bec-k** [comment] 2020-04-13 16:34
> If you remove "js" from the templateFormats array in .eleventy.js, everything should work as you expect. Eleventy will your copy .js files over by default so there's no need to add it there. This is not specifically mentioned in the docs on https://www.11ty.dev/docs/copy/ , perhaps that is something to be looked into.

When I remove `'js` from the templateFormats array in `.eleventy.js` the client-side script is not copied to the `_site` directory.

**Comment by carlos-ds** [comment] 2020-04-13 17:24
My bad, I should've seen that. That only removed the error but doesn't seem to copy the file indeed. 

For your use case, you could rewrite the .eleventy.js as follows to copy all items from _src/scripts.

```
module.exports = function (eleventyConfig) {
	eleventyConfig.setTemplateFormats(["11ty.js", "css", "svg", "jpg", "png"]);
	eleventyConfig.addPassthroughCopy("_src/scripts");

	return {
		dir: {
			data: "_data",
			input: "_src",
			layouts: "../_layouts",
		},
		dataTemplateEngine: "11ty.js",
	};
};
```

Perhaps not as convenient as you'd like but it should do the trick. In one of my projects, I made a top-level folder "assets" and passed all the static files in this way.

**Comment by c-bec-k** [comment] 2020-04-22 18:45
> My bad, I should've seen that. That only removed the error but doesn't seem to copy the file indeed.
> 
> For your use case, you could rewrite the .eleventy.js as follows to copy all items from _src/scripts.
> 
> ```
> module.exports = function (eleventyConfig) {
> 
> 	eleventyConfig.setTemplateFormats(["11ty.js", "css", "svg", "jpg", "png"]);
> 	eleventyConfig.addPassthroughCopy("_src/scripts");
> 
> 	return {
> 		dir: {
> 			data: "_data",
> 			input: "_src",
> 			layouts: "../_layouts",
> 		},
> 		dataTemplateEngine: "11ty.js",
> 	};
> 
> };
> ```
> 
> Perhaps not as convenient as you'd like but it should do the trick. In one of my projects, I made a top-level folder "assets" and passed all the static files in this way.

Is there a way to do the `addPassthroughCopy` with exporting an object like I currently have setup? Or do I have to change it to export a function to make use of that option?

**Comment by carlos-ds** [comment] 2020-04-24 19:32
I'm not really sure but your original question seems about the same issue as #181. That was proposedly fixed in v0.5.1 but it could've popped up again due to regression. Perhaps @zachleat or someone else could confirm that?

**Comment by ethaneisenhard** [comment] 2021-02-18 04:54
Putting this here in case it helps anyone. 

I put all my ```.js``` files in a folder called ```javascript``` at the root of the project

Adding   ```eleventyConfig.addPassthroughCopy("javascript");``` passed all the JS files into ```_site``` folder built by Eleventy 

```
module.exports = function (eleventyConfig) {
  eleventyConfig.setTemplateFormats(["html", "css", "jpg", "liquid"]);
  eleventyConfig.addPassthroughCopy("javascript");
};
```

**Comment by lifeinafolder** [comment] 2021-09-16 03:53
Hi folks, I am seeing this issue again. I am doing the same as @ethaneisenhard . I have a folder called `lib` which holds a simple `main.js` client side javascript file. My `.eleventy.js` config file has this:

```
  eleventyConfig.setTemplateFormats([ "html", "liquid", "njk", "jpg", "png", "jpeg", "webp", "gif"]);

  // Copy all client side javascript
  eleventyConfig.addPassthroughCopy("lib");
```

However, when I make changes to `lib/main.js`, I don't see the file inside `public` output directory getting updated. What am I missing?

**Comment by zachleat** [comment] 2022-06-29 17:13
Sorry for the super late response here but I believe this is a duplicate of https://github.com/11ty/eleventy/issues/1325#issuecomment-691792459

**Comment by zachleat** [comment] 2022-06-29 17:13
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Closed by zachleat** 2022-06-29 17:13 UTC
Labels: needs-triage
