### ISSUE TITLE
Can Eleventy process Liquid tags in YAML frontmatter in a Markdown file?

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#438] opened 2019-03-05 18:41 UTC
Is this possible?

**hello-world.md:**

```yaml
---
title: Hello World
seo_title: {{ page.title }} | {{ site.title }}
---

Lorem ipsum
```

**Comment by zachleat** [comment] 2019-03-06 20:32
I believe this is a duplicate of https://github.com/11ty/eleventy/issues/335

There is an undocumented feature that does this, kinda, some discussion here: https://github.com/11ty/11ty.io/issues/33

**Comment by zachleat** [comment] 2019-03-06 20:32
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-03-06 20:32 UTC
Labels: education
