### ISSUE TITLE
JSON serialization error on gatAll() data (circular dependency)

### ISSUE THREAD

**Issue by wsw70** [11ty/eleventy#872] opened 2020-01-20 14:00 UTC
**Describe the bug**

I am trying to write to a file the  JSON version of the data available from `getAll()`. Trying to `JSON.stringify()` the resulting object throws a `TypeError: Converting circular structure to JSON` 

**To Reproduce**

I added the following content to `.eleventy.js` : 

```
const fs = require('fs');

module.exports = function (eleventyConfig) {
    console.log("in module.exports")

    eleventyConfig.addCollection("allMyContent", function (collection) {
        const metaData = collection.getAll()
        console.log(JSON.stringify(metaData))
        return metaData
    });

    eleventyConfig.setTemplateFormats([
        "md",
        "css",
        "js",
    ]);
};
```

This results in 

```
in module.exports
Problem writing Eleventy templates: (more in DEBUG output)
> Converting circular structure to JSON

`TypeError` was thrown:
    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)
        at Object.allMyContent (D:\Seafile\dev-perso\web sites\eleventy2\.eleventy.js:9:26)
        at TemplateMap.getUserConfigCollection (C:\Users\yop\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateMap.js:451:47)
        at TemplateMap.initDependencyMap (C:\Users\yop\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateMap.js:238:54)
        at TemplateMap.cache (C:\Users\yop\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateMap.js:282:16)
Wrote 0 files in 0.14 seconds (v0.10.0)
Watching…
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:8080
    External: http://192.168.20.10:8080
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 --------------------------------------
[Browsersync] Serving files from: _site
```

Using a raw `console.log(metaData)` (without the stringification) outputs the correct data: 

```
[ { template:
     Template {
       inputPath: './src/posts/premier.md',
       inputDir: 'src',
       parsed: [Object],
       extraOutputSubdirectory: '',
       outputDir: '_site',
       linters: [],
       transforms: [],
       plugins: {},
       templateData: [TemplateData],
       paginationData: {},
       isVerbose: true,
       isDryRun: false,
       writeCount: 0,
       skippedCount: 0,
       wrapWithLayouts: true,
       fileSlug: [TemplateFileSlug],
       fileSlugStr: 'premier',
       filePathStem: '/posts/premier',
       _templateRender: [TemplateRender],
       inputContent:
        '---\r\ntitle: hello\r\ntags: tag1, tag2\r\nquelquechose: wazaa\r\n---\r\n# First post\r\n\r\nHello world!\r\n\r\n**the end**\r\n',
       _config: [Object],
       frontMatter: [Object],
       dataCache: [Object] },
    inputPath: './src/posts/premier.md',
    fileSlug: 'premier',
    filePathStem: '/posts/premier',
    data:
     { pkg: [Object],
       title: 'hello',
       tags: [Array],
       quelquechose: 'wazaa',
       page: [Object],
       collections: [Object] },
    date: 2020-01-20T13:15:12.520Z,
    outputPath: '_site/posts/premier/index.html',
    url: '/posts/premier/',
    templateContent: [Getter/Setter] } ]
```

**Expected behavior**

The data from `getAll()` to be serialized

**Environment:**

- OS and Version: Windows 10
- Eleventy Version: 0.10.0

**Additional context**

The serialization is doable (see https://github.com/11ty/eleventy/issues/871#issuecomment-576266699), there must be something in the structure which refers to itself (?)

**Comment by aaronpeters** [comment] 2020-05-17 23:16
I ran into this too.
The problem is with/in `data.collections`.

I was using `.addCollection` and looping over `collection.getFilteredByTag("something")` to put  `something.data` in an object and then wanted to write that object to disk like so
`fs.writeFileSync('./_site/test.json', JSON.stringify(output));`

Got the circular reference error and to my surprise discovered that `something.data` contained *all* collections, not just the data from the templates with tag = `something` _and_ those collections include the one that is currently in the making with `.addCollection` (as in, the `return` has not yet happened).
This makes no sense to me at all: why add all the collections and why the one that is 'in the making'?

My hacky solution is to remove the `collections` property from `something.data` before doing the `JSON.stringify`

**Comment by MadeByMike** [comment] 2020-10-06 00:46
Yep, the collection object is a circular structure. No bug here. We should probably close this and look to answer the question in #871

**Comment by zachleat** [comment] 2022-12-15 21:53
#266 has the trick, I think!

**Closed by zachleat** 2022-12-15 21:53 UTC
Labels: duplicate, education

**Comment by wernerglinka** [comment] 2023-07-25 22:33
Here is a blogpost about this:  https://justbea.dev/notes/nunjucks-dump/
