### ISSUE TITLE
Documentation for UserConfig type definitions doesn't work in ESM

### ISSUE THREAD

**Issue by sentience** [11ty/eleventy#3127] opened 2023-12-19 11:25 UTC
### Operating system

macOS Sonoma 14.2

### Eleventy

3.0.0-alpha.2

### Describe the bug

The [11ty docs recommend this](https://www.11ty.dev/docs/config/#type-definitions) as the way to get TypeScript-powered autocomplete on the `eleventyConfig` object:

```js
/** @param {import("@11ty/eleventy").UserConfig} eleventyConfig */
module.exports = function (eleventyConfig) {
  // …
};
```

After [converting my Eleventy project](https://github.com/sentience/kevinyank.com/pull/19/files) to ESM per [the 3.0 alpha announcement](https://www.11ty.dev/blog/canary-eleventy-v3/), I found that this autocomplete was no longer working. Updating the type import to reference the actual file path fixes the issue for me:

```js
/** @param { import("@11ty/eleventy/src/UserConfig.js") } eleventyConfig */
export default function (eleventyConfig) {
  // …
};
```

I'm not an expert in JSDoc, so I can't say whether there's a downside to this approach (other than the increased verbosity and dependency on Eleventy's internals), but [it's what I'm using now](https://github.com/sentience/kevinyank.com/pull/20). Absent a better suggestion, the Eleventy 3.0 docs and migration guide will probably need to mention this necessary change to preserve the previously-documented functionality.

### Reproduction steps

1. Clone https://github.com/sentience/kevinyank.com/tree/demo-esm-autocomplete-broken
2. `npm install`
3. Open .eleventy.js in Visual Studio Code.
4. Hover over the `eleventyConfig` parameter on [line 9](https://github.com/sentience/kevinyank.com/blob/778917cab293b62ed1c7b238c29f266da6432531/.eleventy.js#L9). Note that Visual Studio Code annotates it as having type `any`.

### Expected behavior

The type should be annotated as `UserConfig`.

### Reproduction URL

https://github.com/sentience/kevinyank.com/tree/demo-esm-autocomplete-broken

**Comment by rubenwardy** [comment] 2023-12-19 12:12
https://github.com/11ty/eleventy/issues/3097

**Comment by zachleat** [comment] 2023-12-19 13:44
Ah, good catch! I’ll fix the export to include userconfig

**Comment by oliverpool** [comment] 2024-02-22 16:25
In my case I had to add `.default`:
```js
/** @param { import("@11ty/eleventy/src/UserConfig.js").default } eleventyConfig */
export default function (eleventyConfig) {
```

**Comment by zachleat** [comment] 2024-06-11 21:57
Duplicate of #3097, `/** @param {import("@11ty/eleventy").UserConfig} eleventyConfig */` works in 3.0.0-alpha.12+

**Closed by zachleat** 2024-06-11 21:57 UTC
Labels: bug
