### ISSUE TITLE
[RFC] Incremental building

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#416] opened 2019-02-15 21:37 UTC
I would like to take a crack at incremental building in the next year. 

## Summary

As assets are processed during the initial build, we will build a dependency graph of the assets, building an abstract syntax tree of the build. 

This will require us to do a few things:

- Have a method for building an AST for a given template engine, extracting it's unique dependencies. (this is not easy)
- extrapolate dependencies from pagination
- extrapolate dependencies from data used in the page (this is not easy)
- creating a temporary memory and filesystem cache to compare the contents of a source file against the last build
- add the ability to trigger a rebuild of only specific files

This will allow for truly incremental building, by allowing us to:

- track what the relationship between templates and data are
- trigger rebuilds of only the changed template, and the pages that that template is referenced by
- allow persisting this between dev and prod builds

**Comment by zachleat** [comment] 2019-03-09 02:31
Uh, wow—this would be quite a lot of work and a HUGE pull request. This would need to be pared down into individual issues before we move forward!

**Comment by zachleat** [comment] 2019-03-09 02:33
TemplateMap.js has _some_ of this already in upcoming 0.7.2, but certainly not all of it.

**Comment by zachleat** [comment] 2019-09-07 04:24
This is a duplicate of #108. We should coalesce over there!

**Closed by zachleat** 2019-09-07 04:24 UTC
Labels: enhancement

**Comment by pbuzdin** [comment] 2021-11-18 18:52
https://www.11ty.dev/docs/usage/incremental/
