### ISSUE TITLE
I just converted a site from jekyll to 11ty.  How do you do blog categories

### ISSUE THREAD

**Issue by distinctperspective** [11ty/eleventy#776] opened 2019-11-17 03:43 UTC
I wasnt able to find much on how to use the blog post categories.  I got the whole site moved over except the categories.

My site used to take over 45 seconds on Jekyll to rebuild on local machine which is way to slow for development.  Takes about 5 seconds for about 350 pages.

I want to move this structure to 11ty...can someone point me in the direction.
https://clocksharkwf.netlify.com/blog
https://clocksharkwf.netlify.com/blog/category/business

I was able to get just the blog index with pagination working but not categories.

**Comment by Munter** [comment] 2019-11-17 15:39
If you have categories in your front matter you can access these in your eleventy config while adding collections. Register new collections which are filtered down versions of the original ones, containing only the ones matching your categories.

**Comment by Ryuno-Ki** [comment] 2019-11-18 19:07
You can use [`getFilteredByTag()`](https://www.11ty.io/docs/collections/#getfilteredbytag(-tagname-)) for that. Treat your categories as `tags` in Eleventy, for example. Otherwise inspect the [`data` property](https://www.11ty.io/docs/collections/#collection-item-data-structure) of a collection item.

**Comment by clockshark** [comment] 2019-11-19 21:57
I figured out the easiest way was this way below

category.html with 
---
pagination:
  data: collections
  size: 1
  alias: tag
  filter:
    - all
    - nav
    - post
    - posts
    - blogposts
    - featurepages
permalink: /Blog/Category/{{ tag }}/
layout: home
renderData:
  title: "Category “{{ tag }}”"
  permalink: /Blog/Category/{{ tag }}/
---

but now my category pages are not paginated

Any help??

**Comment by zachleat** [comment] 2019-11-26 13:51
Ah this is the double-layer pagination problem. There is a way to do this but it isn’t super friendly right now.

See the example I posted here: https://github.com/11ty/eleventy/issues/332
Also upvote https://github.com/11ty/eleventy/issues/461 if you’d like to see a nicer way integrated into core

**Comment by zachleat** [comment] 2019-11-26 13:52
Closing this as a duplicate of the issues above.

> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-11-26 13:52 UTC
Labels: education
