### ISSUE TITLE
Can Eleventy cache local files and only regenerate changed files like Jekyll?

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy#1666] opened 2021-02-28 17:35 UTC
I'm in the process of migrating my Jekyll blog to Eleventy to take advantage of the better tooling, and so far so good! I seem to have stumbled across a blocker, though.

Jekyll uses a `.jekyll-cache`  directory to cache files and only regenerates the files that changed. This means that once Jekyll has built my site the first time (e.g., upon starting the local server), all subsequent re-builds take only a few seconds (~4 seconds on my machine).

With Eleventy, all files are getting regenerated on my end, and I'm seeing a fivefold increase in build times: roughly 20 seconds for a change to a single file. This is because the server is regenerating files that weren't touched to begin with, like my posts. It also re-copies my assets, and I have a lot of images.

Is there a plugin or build setting that would allow Eleventy to cache things locally and only regenerate changed files/routes? All I'm seeing related to caching in the documentation is browser caching and caching assets from remote sources, like CDNs or image providers.

Thank you!

**Comment by Ryuno-Ki** [comment] 2021-02-28 20:04
Related to #108

**Comment by zachleat** [comment] 2021-03-06 03:57
Yeah, this is a duplicate of #108. Please subscribe over there!

**Closed by zachleat** 2021-03-06 03:57 UTC
Labels: education
