### ISSUE TITLE
Portfolio collection with next/ previous links but unique permalinks

### ISSUE THREAD

**Issue by luminarious** [11ty/eleventy#426] opened 2019-02-22 14:59 UTC
Hey, trying to put together a very basic portfolio site. Documentation is great regarding posts and single pages, but this kind of functionality is harder to suss out.. :/
Portfolio would be a pretty clear example case when documenting this.

**Source**:
* ./project-X/*.(jpg|png|gif|mp4|svg|pdf|zip)
* ./project-X/index.pug
  * tags: portfolio

**Goal**:
* //example.com/project-X/*.(jpg|png|gif|mp4|svg|pdf|zip)
* //example.com/project-X/index.html
  * ˂link rel="canonical" href="//example.com/project-X" /˃
  * <-Prev and Next-> links

**Comment by rendall** [comment] 2019-03-04 20:04
I second this. I really need a way to get access to 'previous' and 'next' in a collection (of posts).

e.g. (something like)
```
  eleventyConfig.addCollection("posts", collection => {  
    const filtered = collection.getFilteredByGlob("./posts/*").sort((a, b) => a.date - b.date);
    const getPost = (i) => i < 0 || i > filtered.length - 1? undefined : filtered[i].data
    const posts = filtered.map((post, i) => ({ ...post, data: { ...post.data, prev: getPost(i - 1), next: getPost(i + 1) } }))
    return posts
   }); 
```
Interestingly enough, the code above *shows* the relevant data inside the collection items, but it does not seem to be accessible from inside templates.

**Comment by zachleat** [comment] 2019-03-11 03:26
I suspect y’all want to follow along at #211 which seems to be a duplicate of this

**Comment by rendall** [comment] 2019-03-14 09:53
@zachleat I don't think this is exactly the same. The other seems to deal with *pagination* which (appears to be) deals with page numbering.  e.g. /some-url/page/1 to /some-url/page/2

This thread is a different animal.  Let's say the collection is ordered by some other sort. Not page number, but, say, date.  It would be nice for the template to have access to the 'next' or 'previous' along some other scheme.

**Comment by thejohnfreeman** [comment] 2019-03-15 16:38
@rendall I think the idea from @zachleat in #211 is this:

- You create a collection of posts.
- You order the collection by date. By default, it is ordered by date ascending; how to change to descending is already documented.
- You paginate the collection, where each page has exactly 1 post.
- Each page has access to the next and previous pages, all of which have exactly 1 post, so this effectively enables linking to the next and previous post by date.

Here's my problem. I tried sticking my posts in a `_posts` directory, creating the collection from that directory in my `.eleventy.js`, and then paginating 1-by-1 like I just described above. It works, but I can't get Eleventy stop creating two copies of my posts: one from the pagination, and one directly from the templates in the `_posts` directory. If I move `_posts` out of my input directory, or if I use `.eleventyignore` to ignore the templates in `_posts`, no pages are created.

**Comment by chinchang** [comment] 2019-05-20 16:35
@thejohnfreeman You can set `permalink: false` in your individual posts. I just hope that doesn't affect the pagination output.

**Comment by thejohnfreeman** [comment] 2019-05-20 21:39
@chinchang I have tried that out (more [here](https://github.com/11ty/eleventy/issues/529)). Then the problem became that if I wanted to link to a post, I would need to manually craft the URL for that post's page in the pagination; I could no longer use the convention `page.url` from Eleventy.

**Comment by borisschapira** [comment] 2019-06-14 07:14
Hey people, how about using the Custom Collection feature to extend the posts themselves during the build?

```
function addPrevNext(collectionArray) {
  const l = collectionArray.length;
  for (let p = 0; p < l; p++) {
    console.log(collectionArray[p]);
    if (p > 1)
      collectionArray[p].data.previous = {
        title: collectionArray[p - 1].data.title,
        url: collectionArray[p - 1].url
      };
    if (p < l - 1)
      collectionArray[p].data.next = {
        title: collectionArray[p + 1].data.title,
        url: collectionArray[p + 1].url
      };
  }
  return collectionArray;
}

eleventyConfig.addCollection("my_posts", 
    collection => addPrevNext(collection.getFilteredByTag("posts"))
);
```

I'm using this with my posts to generate collections of posts for a specific language and a specific category, and have previous/next post inside the collection:

```
arrLocales = ["en", "fr"];
arrCategories = ["web", "citoyen", "papa"];

for (let i = 0; i < arrLocales.length; i++) {
  let l = arrLocales[i];
  eleventyConfig.addCollection(`posts_${l}`, collection =>
    collection.getFilteredByTag("posts").filter(function(item) {
      return item.data.locale == l;
    })
  );

  for (let j = 0; j < arrCategories.length; j++) {
    let c = arrCategories[j];
    eleventyConfig.addCollection(`posts_${l}_${c}`, collection =>
      addPrevNext(
        collection.getFilteredByTag("posts").filter(function(item) {
          return item.data.category == c && item.data.locale == l;
        })
      )
    );
  }
}
```

**Comment by rendall** [comment] 2019-06-14 08:55
Hey, awesome. I will try that, this weekend.

**Comment by alukito** [comment] 2019-10-07 01:22
Hi @borisschapira, the custom collection works well for this case, thank you. One note on your code example though. I think the index guard `if (p > 1)` will exclude first and second item, while we generally would like to exclude only the first item, so maybe it should be `if (p > 0)`.

**Comment by zachleat** [comment] 2020-01-18 05:26
On re-read I believe this is a duplicate of #529 which has a nice workaround. Let’s coalesce over there.

**Closed by zachleat** 2020-01-18 05:26 UTC
Labels: duplicate, waiting-to-close
