### ISSUE TITLE
Behaviour of {{content}} tag in 11ty layout template inheritance

### ISSUE THREAD

**Issue by danfascia** [11ty/eleventy#448] opened 2019-03-13 22:14 UTC
When using the 11ty built in `layout: <layout_name>` in front-matter the `{{content}}` tag from downstream child templates returns rendered HTML rather than plain text.

This is a problem if you wish to create derivations of the markdown body content, such as dynamic excerpts.

This problem can be circumvented by using `{% extends <layout> %}` with {% blocks %} to pass data back to parent templates.

**Recommendation:**
Could we consider a special {{rawContent}} tag which will always contain the unprocessed plain text?

**Comment by zachleat** [comment] 2019-03-14 00:21
I like this idea, per our conversation. How do you get rid of the markdown formatting in your markdown excerpt?

**Comment by zachleat** [comment] 2019-03-23 02:14
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Closed by zachleat** 2019-03-23 02:14 UTC
Labels: enhancement

**Comment by zachleat** [comment] 2025-11-07 20:45
Duplicate of #1206 (shipped with v3)
