### ISSUE TITLE
Globally set default layout?

### ISSUE THREAD

**Issue by osmarks** [11ty/eleventy#380] opened 2019-01-12 11:01 UTC
Is there some way to globally set the `layout` property? Using a global data file doesn't work, since the values in them don't override the top-level ones.

**Comment by zachleat** [comment] 2019-01-13 05:17
You can use directory data files but they do not work yet in the project root, only in subfolders. See #245 for that request.

So to answer your question: kind-of. I would consider this request to be a duplicate of #245 though, which would complete this request too. Can you upvote and follow along there?

**Comment by zachleat** [comment] 2019-01-13 05:17
Directory data files: https://www.11ty.io/docs/data-template-dir/

**Comment by zachleat** [comment] 2019-01-13 05:18
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-01-13 05:17 UTC
Labels: duplicate, enhancement

**Comment by KyleMit** [comment] 2019-12-20 18:18
The challenge is, when using a [global data object](https://www.11ty.dev/docs/data-global/) in the `_data` directory, the returned values are set on a property with the same name as the file

So if you have the following file:

`_data/data.json`

And it contains the following JSON object:

```json
{ "layout": "default.njk" }
```

The resulting global data object will look like this:

![data.json data](https://user-images.githubusercontent.com/4307307/71280307-ce98b600-2328-11ea-9477-b66fc455e273.png)

But there's nothing special about `data.data.layout` - the `layout` property needs to be set on the top level object.  

We can make this work in our favor by naming the file with the property name we'd like to set, and then using JS (not json) to return a plain string value.

So add the following file:

`_data/layout.js`

And add whatever value you want for you default layout page:

```js
module.exports = "default.njk"
```

Which will now set the value at the appropriate depth

![layout.js data](https://user-images.githubusercontent.com/4307307/71280340-e96b2a80-2328-11ea-86ca-75d371bdd813.png)

This is really nice if you'd like to process markdown files with your own custom styles that typically have to live at the root directory of your project (and don't want to add frontmatter to them)

* README.md
* CONTRIBUTING.md
* CODE_OF_CONDUCT.md
* CHANGE_LOG.md

And voila! Docs published to your site, instead of only visible through github

![Contributing page](https://user-images.githubusercontent.com/4307307/71281053-fe48bd80-232a-11ea-8ace-63a55589b26f.png)

**Comment by jackmawer** [comment] 2020-01-08 10:20
@KyleMit just to say thanks, this is a really useful workaround!

**Comment by keenanpayne** [comment] 2020-08-10 22:15
@KyleMit Thank you so much for providing a workaround, as well as some clarity around why and how the workaround works. It's greatly appreciated.

**Comment by svivian** [comment] 2020-10-02 23:43
I'm new to 11ty so apologies if this is a stupid question, but why can't this just be a config option in `.eleventy.js`? i.e.

	module.exports = {
		layout: "mylayout.njk"
	};

**Comment by Guillaume-Mayer** [comment] 2020-11-22 18:32
I tried the workaround but it didn't work for me.
It seems that the js files in the _data directory are not loaded, not sure why.
But putting the name of the layout in a json worked.
In _data/layout.json: `"base.liquid"`
If it can help someone.

**Comment by jeremytarpley** [comment] 2021-10-03 02:34
Just starting to learn 11ty and was trying to figure out how to set a global default layout - adding this in case it helps other beginners. Found two ways:

**Method 1: Add a data file at the top level of your source folder.** It needs to have the same name as the folder. For example, if your source folder is named src, the file would be src.11tydata.js or src.11tydata.json

src/src.11tydata.js
```js
module.exports = {
  // Set a default layout for everything in the src folder and below.
  layout: "layouts/default.njk"
}
```

**Method 2: In the _data folder, add a file named layout.js** (This one is mentioned above. In this case, the format is a little different, it needs to be a string. Don't know enough yet to know why.)

_data/layout.js
```js
module.exports = "default.njk"
```

**Comment by Muhammed-Rahif** [comment] 2024-11-23 14:11
It's almost end of 2024 and you can do this by using `eleventyConfig.addGlobalData` without adding any additional file to you project other than `eleventy.config.js`. Somewhere inside `eleventy.config.js`:
```js
eleventyConfig.addGlobalData("layout", "layout/layout.njk");
```
