### ISSUE TITLE
Adding custom watch target doesn't inject CSS on initial file change (save) event

### ISSUE THREAD

**Issue by ryanscherler** [11ty/eleventy#847] opened 2020-01-09 00:12 UTC
**Describe the bug**
It seems that when adding a custom [watch target](https://github.com/eastslopestudio/eleventy-starter/blob/master/.eleventy.js#L9) such as `src/assets/`, [BrowserSync](https://github.com/eastslopestudio/eleventy-starter/blob/master/.eleventy.js#L50) is not live updating the CSS after the initial save to that directory (e.g. `src/assets/css/app.css`), but when saved again, it is injected.

**To Reproduce**
Clone this repo: https://github.com/eastslopestudio/eleventy-starter

1. Follow setup setup instructions [`npm install etc...`]
2. Run `npm run start` to fire things up
3. Go to an arbitrary source CSS file such as `src/assets/css/app.css` and then add something high level such as `body { background: red }` and watch for live changes to the site. It likely won't work, BUT, save it again (no changes, just save), and bam, it updates the BrowserSync timestamp (and thus injects the new changes).

**Expected behavior**
The file change to one of the CSS files in the `src/assets/` in the [watched folder](https://github.com/eastslopestudio/eleventy-starter/tree/master/src/assets) triggers an immediate BrowserSync event and injects changes on initial save.

**Environment:**
- OS and Version: MacOS 10.15.2
- Eleventy Version: 0.10.0

**Comment by chasemccoy** [comment] 2020-06-30 00:59
Yep, I'm seeing this too

**Comment by chasemccoy** [comment] 2020-06-30 01:08
@zachleat This is quite an old issue... would it be helpful to refile this? It seems this could definitely be triaged as a bug.

**Comment by mmatuzovic** [comment] 2020-06-30 05:04
If I remember correctly, I was able to fix this by removing `./src/assets/css/*` from my .gitignore file.

https://github.com/11ty/eleventy/issues/483

**Comment by ryanscherler** [comment] 2020-06-30 19:09
> If I remember correctly, I was able to fix this by removing `./src/assets/css/*` from my .gitignore file.
> 
> #483

I have since moved to a different method of compiling my CSS and no longer need this, but I also do recall solving this with making sure the the .gitignore didn't have the CSS reference. I'm thinking we can close this issue out and potentially reference this issue in a follow up regarding general watch target issues?

**Comment by chasemccoy** [comment] 2020-06-30 19:15
In this case, I specifically _wanted_ my CSS files to be ignored by git. I was able to solve this by turning off Eleventy's `gitignore` detection and then adding `node_moduled` to my `.eleventyignore` file. Still, it would be nice if added watch targets bypassed the gitignore by default! 

Thanks for the help!

**Comment by zachleat** [comment] 2022-06-29 21:55
I think this is a duplicate of #893 (which has a bit more info and discussion there)

Please follow along over there!

**Closed by zachleat** 2022-06-29 21:55 UTC
Labels: duplicate
