### ISSUE TITLE
Faster boosting time if no changes happen since last build.

### ISSUE THREAD

**Issue by magua-io** [11ty/eleventy#2022] opened 2021-10-12 20:26 UTC
**Is your feature request related to a problem? Please describe.**
No matter whether any files got changed or not, Eleventy always tries to perform "writing templates" to serve the pages.

**Describe the solution you'd like**
I hope there is way to start the server faster without writing templates if possible. Maybe just serve with the cache.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zachleat** [comment] 2021-10-16 19:40
Duplicate of #108, specifically this is requesting cold-start incremental

**Closed as completed by zachleat** 2021-10-16 19:40 UTC
Labels: duplicate, enhancement
