### ISSUE TITLE
Redefining Nunjucks environment causes significant impact to other rendering behavior

### ISSUE THREAD

**Issue by AramZS** [11ty/eleventy#1879] opened 2021-07-05 20:00 UTC
**Describe the bug**

I would like to add some custom environmental settings to the Nunjucks environment. It would be nice to be able to add these [through some sort of filtering of the default behavior, but as far as I can tell that is not available](https://github.com/11ty/eleventy/issues/895). So instead I needed to redefine the Nunjucks. Depending on how I redefine it there are significant unexpected errors that block the rendering process. 

**To Reproduce**

`{% raw %}` tags do not work when I define it as a `new Nunjucks.Environment` nor does `js` front matter on njk files. 

Here is the configuration in my .eleventy.js file, attempting to duplicate the version of this initiation in eleventy's core files:

Note, `siteConfiguration` is the eleventy configuration object returned at the end of the module.exports function. It looks like this: 

```javascript
module.exports = function (eleventyConfig) {
	var siteConfiguration = {

		templateFormats: ["md", "njk", "html"],


		markdownTemplateEngine: "njk",

		htmlTemplateEngine: "njk",

		dataTemplateEngine: false,

		dir: {
			input: "src",
			includes: "_includes",
			layouts: "_layouts",
			data: "_data",
			output: "docs",
		},
	};
```

and here is the initiation:

```javascript
	const normalize = require("normalize-path");

	...

	const pathNormalizer = function(pathString){
		return normalize(path.normalize(path.resolve(".")))
	}

	let nunjucksEnvironment = new Nunjucks.Environment(
		new Nunjucks.FileSystemLoader([
			pathNormalizer(siteConfiguration.dir.includes),
			pathNormalizer(siteConfiguration.dir.layouts),
			pathNormalizer(".")
		]),
		{
			throwOnUndefined: throwOnUndefinedSetting
		}
	);
	eleventyConfig.setLibrary("njk", nunjucksEnvironment);
```

It causes this raw block to fail in my markdown file (preceding graf included):

> And I can also change my passthroughs in `.eleventy.js`.

> {% raw %}

> ```javascript
>	eleventyConfig.addPassthroughCopy({
>		"dinky/_sass": "sass/dinky/_sass",
>	});
>	eleventyConfig.addPassthroughCopy({
>		"src/_sass": "sass/src/_sass",
>	});
> ```
>
> {% endraw %}

Error is thrown at the fourth quote mark (final one on this line): `"dinky/_sass": "sass/dinky/_sass",`

and the following front matter block to break 

```liquid
---js
{
  "eleventyExcludeFromCollections": true,
  "metadata": {
    "title": "...",
    "subtitle": "Notes on various projects",
    "url": (function(){ return process.env.DOMAIN + "/" })(),
    "feedUrl": (function(){ return process.env.DOMAIN + "/rss/" })(),
	"lastBuildDate": (function(){
		var date = new Date();
		return date.toUTCString()
	})(),
    "author": {
      "name": "...",
      "email": "..."
    }
  },
  "internalPageTypes": [ "feed" ]
}
---
```

Error is thrown following the final parenthesis. Over here: `})(),`.

The other way I tried to initiate the environment with my variables was like this:

```javascript
	let nunjucksEnvironment = Nunjucks.configure(
		new Nunjucks.FileSystemLoader([
			siteConfiguration.dir.includes,
			siteConfiguration.dir.input,
			"."
		]),
		{
			throwOnUndefined: throwOnUndefinedSetting,
			autoescape: true
		}
	);
	eleventyConfig.setLibrary("njk", nunjucksEnvironment);
```

The result here is that the files in `_layouts` (specifically at `siteConfiguration.dir.layouts`) are not accessible to Nunjucks, which throws an error: 

` Error: template not found: base.njk`

where `base.njk` resides at `src/_layouts/base.njk`

If I eliminate the troublesome files in the previous configuration that have bad front matter or escaping, I get this error there as well. 

None of this is expected behavior. I would not expect from the documentation or the code in eleventy's core files to have filters stop working in the expected way or the documented expected rendering behavior of Nunjucks to significantly change... yet both things appear to be happening and I'm at a loss as to why. 

For further debugging purposes, the iteration of my site where this error is occurring is at the following commit: https://github.com/AramZS/devblog/tree/f8732c00f54cbf1bf2b50e258b0bb8500af58487

**Expected behavior**

I should be able to either change the configuration of the default Nunjucks behavior in eleventy [via a process like the one in Issue 895](https://github.com/11ty/eleventy/issues/895). Or I should be able to set up a new environment with Nunjucks without causing anticipated default behavior of the rest of eleventy to change. Alternatively, if I've really screwed something up in how I've done this, then some documentation about this that is clearer is needed on the eleventy site, as I've checked there and in the code and in a number of other locations and not seen a clear solution. 

**Screenshots**

**Environment:**

- OS and Version: OSX 11.4
- Eleventy Version 0.12.1

Packages:

```json
{
    "@11ty/eleventy": "^0.12.1",
    "@11ty/eleventy-navigation": "^0.2.0",
    "@11ty/eleventy-plugin-rss": "^1.1.1",
    "@11ty/eleventy-plugin-syntaxhighlight": "^3.1.1",
    "@quasibit/eleventy-plugin-sitemap": "^2.1.4",
    "del": "^2.2.2",
    "highlight.js": "^11.0.1",
    "markdown-it": "^10.0.0",
    "markdown-it-replace-link": "^1.1.0",
    "markdown-it-todo": "^1.0.5",
    "sass": "^1.34.1",
    "dotenv": "^10.0.0",
    "normalize-path": "^3.0.0",
    "nunjucks": "^3.2.3",
    "prismjs": "^1.23.0"
  }
```

**Additional context**

[Repo at time of error](https://github.com/AramZS/devblog/tree/f8732c00f54cbf1bf2b50e258b0bb8500af58487).

Thanks for the help!

**Comment by pdehaan** [comment] 2021-07-05 21:38
Can you explain this code to me?

```js
const pathNormalizer = function (pathString) {
  return normalize(path.normalize(path.resolve(".")));
};

// Nunjucks Filters
let nunjucksEnvironment = new Nunjucks.Environment(
  new Nunjucks.FileSystemLoader([
    pathNormalizer(siteConfiguration.dir.includes),
    pathNormalizer(siteConfiguration.dir.input),
    pathNormalizer("."),
  ]),
  {
    throwOnUndefined: throwOnUndefinedSetting,
    autoescape: true,
  }
);
eleventyConfig.setLibrary("njk", nunjucksEnvironment);
```

---

If I separate the `Nunjucks.FileSystemLoader` array into a separate variable and log that, it starts to get a bit interesting:

```js
const njkLoaderArr = [
	pathNormalizer(siteConfiguration.dir.includes),
	pathNormalizer(siteConfiguration.dir.layouts),
	pathNormalizer(siteConfiguration.dir.input),
	pathNormalizer("."),
];

console.log({njkLoaderArr});
```

Then I get this output:

```js
{
  njkLoaderArr: [
    '/private/tmp/devblog',
    '/private/tmp/devblog',
    '/private/tmp/devblog',
    '/private/tmp/devblog'
  ]
}
```

Not exactly what I was expecting, but I believe part of the issue comes from your `pathNormalizer()` which hardcodes `"."` and isn't using the specified `pathString` attribute.

```js
return normalize(path.normalize(path.resolve(".")));
```

Changing that to use the `pathString` and rebuilding the site is still giving me errors locally, but getting closer.

```diff
-return normalize(path.normalize(path.resolve(".")));
+return normalize(path.normalize(path.resolve(pathString)));
```

```js
{
  njkLoaderArr: [
    '/private/tmp/devblog/_includes',
    '/private/tmp/devblog/_layouts',
    '/private/tmp/devblog/src',
    '/private/tmp/devblog'
  ]
}
```

Sorta kinda works... but the paths to `_includes/` and `_layouts/` is wrong, since those are within your `siteConfiguration.dir.input` directory (aka: "src/").

A few different ways to solve this, but this was the first thing I tried:

```js
const {includes, layouts, input} = siteConfiguration.dir;
const njkLoaderArr = [
	pathNormalizer(path.join(input, includes)),
	pathNormalizer(path.join(input, layouts)),
	pathNormalizer(input),
	pathNormalizer(".")
];

console.log({njkLoaderArr});
```

Behold:

```js
{
  njkLoaderArr: [
    '/private/tmp/devblog/src/_includes',
    '/private/tmp/devblog/src/_layouts',
    '/private/tmp/devblog/src',
    '/private/tmp/devblog'
  ]
}
```

And now the site will build without errors. 
Not sure if that gets you closer to an answer or solution, but seemed to get me past the build errors locally. 🤷

**Comment by pdehaan** [comment] 2021-07-06 01:17
More context in https://github.com/AramZS/devblog/pull/1

**Comment by zachleat** [comment] 2021-08-06 16:36
I think this is a duplicate of #895 right? We need a `setNunjucksOptions`

**Comment by zachleat** [comment] 2021-08-06 16:36
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Closed by zachleat** 2021-08-06 16:36 UTC
Labels: needs-triage

**Comment by AramZS** [comment] 2021-08-20 15:46
Thanks to @pdehaan for helping me debug the core issue, I agree this was an issue out of confusing trying to pass options to a new Nunjucks environment, so put my vote behind the idea of a `setNunjucksOptions` function! There may be some other issue here that I'm still trying to work through, but it doesn't appear to be an 11ty issue, so this ticket can remain closed.
