### ISSUE TITLE
SASS custom template example not working with @use or @import

### ISSUE THREAD

**Issue by smth** [11ty/eleventy#2258] opened 2022-03-03 15:55 UTC
I've just tried using the [SASS custom template language with inputPath example](https://www.11ty.dev/docs/languages/custom/#using-inputpath), and I'm finding that changes made to files that are being used (`@use`) or imported (`@import`) are not not making it to the final CSS file. Everything appears to run according to the terminal, but the new SASS is not compiled. Changes do appear after restarting Eleventy.

**Comment by MWDelaney** [comment] 2022-03-08 15:53
I can confirm. I also had difficulty getting the documentation example working. Here's what worked for me:

```js
    let config = {
      // Set the output file extension
      outputFileExtension: "css",

      // Compile should return a string
      compile: function (inputContents, inputPath) {
        let parsed = path.parse(inputPath);
        if(parsed.name.startsWith("_")) {
          return;
        }

        return (data) => {
          // Include scss from anywhere in the project
          let includesPaths = [this.config.dir.includes];

          // Legacy function, but still supported
          let result = sass.renderSync({
            file: inputPath,
            includesPaths,
            data: inputContents,
            outputStyle: "compressed",
          });

          // Return the rendered CSS as a string
          return result.css.toString("utf8");
        };
      }
    }
```

**Comment by DanCorderSoftwire** [comment] 2022-03-23 18:10
I've also been affected by this. I think the way it works is that the `compile` function is called whenever an SCSS file is changed so that eleventy can get a new function to generate the corresponding CSS file.
If the top level file doesn't change then eleventy just re-uses the function originally returned by `compile`. In the docs `result` is only refreshed when a top level file changes, so although changing an import will cause eleventy to re-run the generation function for the top level SASS/CSS that function will continue to use the old `result` value.
To work around this we can move the result calculating code into the function returned by `compile` instead.

This is working for me:

```
    eleventyConfig.addTemplateFormats("scss");
    eleventyConfig.addExtension("scss", {
        outputFileExtension: "css",

        compile: async function(inputContent, inputPath) {
            let parsed = path.parse(inputPath);
            if(parsed.name.startsWith("_")) {
                return;
            }

            return async (data) => {
                let result = sass.compileString(inputContent, {
                    loadPaths: [ parsed.dir ]
                });

                return result.css;
            };
        }
    });
```

This is slightly inefficient in that all top level SASS files will be recalculated whenever any SASS file changes, but I can't see a way around that, and if you're using imports then you probably have very few top level files anyway.

**Comment by zachleat** [comment] 2022-04-15 20:09
The most straightforward way to fix this is to disable the compile cache:

```
compileOptions: {
  cache: false
},
```

https://www.11ty.dev/docs/languages/custom/#compileoptions.cache-for-advanced-control-of-caching

**Comment by zachleat** [comment] 2022-04-15 20:11
Given that we don’t have access to the full dependency tree of a template language to know whether or not another file relates to the current file’s cache, I think it might be prudent to change the default of the compile cache setting in 2.0 to be `false`.

**Comment by sguter90** [comment] 2022-04-24 12:55
I wanted to add an additional note for people using the ``--incremental`` option in combination with SASS:
https://www.11ty.dev/docs/usage/incremental/

This will not work even if the compile cache is disabled. (Which somehow makes sense based on the docs)  

In my case I was using [@grimlink/eleventy-plugin-sass](https://github.com/GrimLink/eleventy-plugin-sass#readme) which per default has disabled compile cache.  
But because my npm script was using ``npx eleventy --incremental --serve`` changes created in imported sass files did not get applied.
As soon as I removed the ``--incremental`` option everything worked fine.

Maybe this helps some other people which also use some kind of template and didn't remember they are using incremental builds 😆

**Comment by zachleat** [comment] 2022-09-28 16:30
Notably the default cache key did change for this in 2.0.0-canary.16 https://github.com/11ty/eleventy/commit/ea7414069ca0afd44271c48d9e6b0487dbf7ff52

But just as disclosure this is unlikely to fix the issue presented here.

**Comment by zachleat** [comment] 2022-12-09 16:15
@sguter90 A note that `--incremental` does work fine for this use case with the compile cache disabled, assuming you’re storing your included files in the Eleventy includes directory. See https://www.11ty.dev/docs/languages/custom/#using-inputpath

If you aren’t storing those files in your includes directory, you can override `isIncrementalMatch` to force this behavior (still with compile cache disabled).

I did add some additional documentation for the `isIncrementalMatch` option this morning if you’d like to read about it (or extend it): https://www.11ty.dev/docs/languages/custom/#isincrementalmatch

Here’s a sample of what I mean:

```js
eleventyConfig.addExtension("scss", {
	outputFileExtension: "css", // optional, default: "html"
	compileOptions: {
		cache: false
	},
	isIncrementalMatch: function(modifiedFile) {
		// modifiedFile.startsWith("_") is the magic addition here
		if (!this.isFullTemplate || modifiedFile.startsWith("_")) {
			return true;
		}
		if (this.inputPath === modifiedFile) {
			return true;
		}
		return false;
	},
	compile: function (inputContent, inputPath) {
		let parsed = path.parse(inputPath);

		let result = sass.compileString(inputContent, {
			loadPaths: [
				parsed.dir || ".",
				this.config.dir.includes
			]
		});

		return (data) => {
			return result.css;
		};
	}
});
```

**Comment by zachleat** [comment] 2022-12-10 02:45
Alright after all of this, I think the easiest short-term workaround here is to disable compile cache.

After looking at this code and comparing it to incremental implementations I wrote for the Vue and WebC plugins, I put in a bunch of work to streamline this for folks. Specially, I’ve added an `addDependencies` method bound to the `compile` callback that you can use to declare dependencies both for for-free incremental matching and cache key computation.

The sass `compileString` function includes a `loadedUrls` property (an rray of `URL` objects) in the result that can be used to implement this, e.g.:

```
[
  URL {
    href: 'file:///Users/zachleat/Temp/eleventy-issue-2258/_includes/_code.scss',
    protocol: 'file:',
    pathname: '/Users/zachleat/Temp/eleventy-issue-2258/_includes/_code.scss',
    // some output truncated
  }
]
```

This simplifies our example down to:

```js
const path = require("path");
const sass = require("sass");

module.exports = function(eleventyConfig) {
	eleventyConfig.addTemplateFormats("scss");

	eleventyConfig.addExtension("scss", {
		outputFileExtension: "css", // optional, default: "html"

		compile: function (inputContent, inputPath) {
			let parsed = path.parse(inputPath);
			let result = sass.compileString(inputContent, {
				loadPaths: [
					parsed.dir || ".",
					this.config.dir.includes
				]
			});

			// This is the new API using Sass’ `loadedUrls`
			let dependencies = result.loadedUrls.filter(dep => dep.protocol === "file:").map(entry => {
				return path.relative(".", entry.pathname);
			});
			this.addDependencies(inputPath, dependencies);

			return (data) => {
				return result.css
			};
		}
	});
};
```

I’ll update the docs for this on Monday but it should be operating correctly with what’s on GitHub now (it needs some more tests before I can close this one out)

**Closed** 2022-12-12 17:57 UTC
Labels: bug, documentation, feature: 🤟 custom template languages

**Comment by Pleune** [comment] 2022-12-28 20:01
I am not able to get this working with canary.23

I get a "Node does not exist" error from `dependency-graph/lib/dep_graph.js:271`. I can prevent this error by adding the `__connections:` prefix to the dependency paths with: `let deps = loadedUrls.map((fileURL) => '__collection:' + path.relative(".", url.fileURLToPath(fileURL)).split(path.sep).join(path.posix.sep));` before `this.addDependencies(inputPath, deps);`, but incremental builds never rebuild the main SASS file.

**Comment by seb-celinedesign** [comment] 2023-01-06 09:28
@Pleune 11ty canary-24 fix the issue for me

**Comment by zachleat** [comment] 2023-01-06 21:33
Ah yeah sorry for not circling back here—I did fix this in canary.24—thank you for confirming!
