### ISSUE TITLE
ignore when copying

### ISSUE THREAD

**Issue by tcurdt** [11ty/eleventy#1396] opened 2020-09-05 22:22 UTC
I have some files `_*.html` that I do not want to get copied over.
Unfortunately it's not easy to exclude them when using globbing.

    config.addPassthroughCopy("src/**/*.html");

I tried adding

    **/_*.html

to `.eleventyignore` but that does not work either.

Is the latter a bug?

**Comment by tcurdt** [comment] 2020-09-06 12:27
This seems to be related: https://github.com/11ty/eleventy/issues/1134

**Comment by binyamin** [comment] 2020-09-06 16:27
@tcurdt Do you mind spinning up an example repo? I tried it [on github](https://github.com/binyamin/11ty-Test-Tube/tree/11ty/eleventy%231396) (and you can run it online [on gitpod](https://gitpod.io/#snapshot/68bad070-d3d9-45fe-9bbc-22270267e320
)), but couldn't reproduce your issue.

**Comment by tcurdt** [comment] 2020-09-06 16:29
Interesting. Then I will prepare something. Odd. Thanks for trying!

**Comment by tcurdt** [comment] 2020-09-06 16:42
Had to give gitpod a try https://gitpod.io/#snapshot/df8f16f3-8ace-4d0c-b151-64e603553012 :) but also exported a tgz.

[11ty-Test-Tube.tar.gz](https://github.com/11ty/eleventy/files/5179969/11ty-Test-Tube.tar.gz)

**Comment by binyamin** [comment] 2020-09-06 16:55
Thanks. Now that I see the setup, I'm not really sure why you're using passthrough file copy. 11ty considers `.html` a valid template extension, so I can't think what adding it to the config will do.

**Comment by tcurdt** [comment] 2020-09-06 17:07
@binyamin Maybe I am just misunderstanding the point of a passthrough copy? But my config looks like this

    for (const ext of [
      'html',
      'css',
      'jpg',
      'png',
      'gif',
      'svg',
      'java',
      'sh',
    ]) {
      config.addPassthroughCopy("src/**/*." + ext);
    }

    return {
      dir: {
        input: 'src',
        output: 'site',
      },
      templateFormats: [
        'njk',
        'md',
      ],
      htmlTemplateEngine: 'njk',
      markdownTemplateEngine : "njk",
      passthroughFileCopy: true,
    }

I guess this may be a problem for other extensions nevertheless.

**Comment by binyamin** [comment] 2020-09-06 17:25
I still don't understand what you're accomplishing by `config.addPassthroughCopy("src/**/*.html");`.

Also, would it work to modify the glob "src/**/*.html" so that it negates any file starting with an underscore? (Something like `src/**/!(_*).html`)

**Comment by tcurdt** [comment] 2020-09-06 17:44
@binyamin I don't see why I would **not** have to copy `html` files if my templates are only `md` and `njk`. Can you elaborate?

Negating the glob would of course work, too. I wasn't aware that's an option.
I'd only know how to do this with a regular expression.

I guess I can close this issue as duplicate of it #1134 which I do think is worth fixing.

**Comment by binyamin** [comment] 2020-09-06 17:50
> I don't see why I would **not** have to copy `html` files if my templates are only `md` and `njk`. Can you elaborate?

Oh, gotcha. Yeah, I guess you should use the special glob syntax until #1134 is fixed.

**Comment by binyamin** [comment] 2020-09-06 17:50
Closing in favor of #1334

**Closed by binyamin** 2020-09-06 17:50 UTC
Labels: education
