### ISSUE TITLE
Example on how to achieve pagination

### ISSUE THREAD

**Issue by ajmalafif** [11ty/eleventy#345] opened 2018-12-15 18:25 UTC
I have tried searching through the docs and github issues and apply them all, and none of it working for me. 

I think I am missing something substantial here. I'll looking to apply this kind of pagination for my blogpost:
![screenshot 2018-12-16 02 22 00](https://user-images.githubusercontent.com/827167/50046160-88879180-00d9-11e9-8e9c-74333a2c1159.png)

image credit to: https://dribbble.com/shots/2351417-What-s-your-fav-pagination/attachments/449743

I am using this boilerplate as my starting point: https://github.com/danurbanowicz/eleventy-netlify-boilerplate

My suspicion is I can't use `- post` as my tag since it's already been used? I plan to write a tutorial for this for non-technical users of 11ty (I am a designer) after I figure this out because it's way too painful to do this with 11ty.

**Comment by zachleat** [comment] 2018-12-17 05:01
Can you include your pagination template code here and I help specifically with your problem?

**Comment by ajmalafif** [comment] 2018-12-18 18:24
Hi @Vassi, appreciate the help! I did give above a try but it doesn't work. Maybe I apply it wrongly. 

I am guessing this code here goes to `blog.njk`:
```
---
title: My Posts
pagination:
  data: collections.post
  size: 6
  alias: posts
---

<ol>
{% for post in posts %}
  <li><a href="{{ post.url | url }}">{{ post.data.title }}</a></li>
{% endfor %}
</ol>
```
But where do I put this code tho? 
```
{
  items: [], // current page’s chunk of data
  pageNumber: 0, // current page number, 0 indexed

  // Cool URLs, added in v0.6.0
  nextPageHref: "…", // put inside <a href="">Next Page</a>
  previousPageHref: "…", // put inside <a href="">Previous Page</a>
  firstPageHref: "…",
  lastPageHref: "…", 
  hrefs: [], // all page hrefs (in order)

  // Uncool URLs (these include index.html file names)
  nextPageLink: "…", // put inside <a href="">Next Page</a>
  previousPageLink: "…", // put inside <a href="">Previous Page</a>
  firstPageLink: "…", // added in v0.6.0
  lastPageLink: "…", // added in v0.6.0
  links: [], // all page links (in order)
  pageLinks: [], // deprecated alias to `links`

  data: …, // pointer to dataset
  size: 1, // chunk sizes
}
```

Thanks again!

**Comment by Vassi** [comment] 2018-12-18 18:37
The second bit is what's inside the pagination variable.

So today you have this in your layout:

```
---
layout: layouts/base.njk
section: blog
---
<section class="w-100 mt4 mt5-ns">
  <article class="mt6 wrap dt bb b--light-gray">
    <div class="fl w-100 w-50-ns tc tl-ns pb0 pb4-ns">
      <h1 class="mb1 mt0">Blog</h1>
      <p class="moon-gray mt0">Personal learnings & thoughts</p>
    </div>
    <div class="fl w-100 w-50-ns ph4 ph0-ns lh-copy">
      <p>I enjoy writing down and reflect on my experience. My goal is to write more about design, frontend and anything in between.</p>
    </div>
  </article>
</section>

{{ layoutContent | safe }}

{% set postslist = collections.posts %}
{% include "components/postslist.njk" %}
```

I would move the last two lines to your blog.md page (since it uses your layout)

and maybe try: 
```
---
layout: layouts/blog.njk
title: Blog | @ajmalafif
tags:
  - nav
navtitle: Blog
date: 2017-01-01
pagination:
  data: collections.post
  size: 6
  alias: postslist
---

{% include "components/postslist.njk" %}
```
I omitted the set because the alias should already be creating the postslist variable your component wants

**Comment by ajmalafif** [comment] 2019-01-07 19:12
I just realized there's no code for  something like `< Prev | 1 | 2 | 3 | Next >` so maybe what I am thinking is actually not available on eleventy.

**Comment by freshyill** [comment] 2019-03-18 16:49
I'm finding pagination to be _very_ confusing with Eleventy. 

I'm really not sure what any of the pagination stuff does, because when I try the examples, it doesn't produce what I'd call pagination… I'd say it just makes lists. 

## Questions I still have: 

1. Is what @ajmalafif is asking about even possible? He closed this under the assumption that it's not, but nobody ever confirmed it. I don't think this is a very good resolution.
2. Where the heck does that big javascript object go? The docs just say " Here’s what’s in pagination:" Does this go as json in the frontmatter? In eleventy.js? It's really confusing.
3. What does `size` mean? Posts per page? Total number of pages? Something else? It's very unclear. 
4. If it's possible, can somebody please just share some working code showing how to produce something like what @ajmalafif was trying to produce?
5, If it's not possible, can someone share something similar? How close to this can you get?

![50046160-88879180-00d9-11e9-8e9c-74333a2c1159](https://user-images.githubusercontent.com/879292/54547152-91f3f480-497b-11e9-8849-5f95dde01631.png)

@ajmalafif did you ever find a solution?

**Comment by ajmalafif** [comment] 2019-03-18 17:12
@freshyill hey

**Comment by zachleat** [comment] 2019-11-02 04:18
Howdy y’all, I made a dedicated documentation page just for this, please have a look! https://www.11ty.io/docs/pagination-nav/

**Closed by zachleat** 2019-11-02 04:18 UTC
Labels: documentation, education

**Comment by zachleat** [comment] 2019-11-04 22:01
Hey y’all, over the weekend I added a new tutorial on this here: https://www.11ty.io/docs/pagination-nav/

**Comment by distinctperspective** [comment] 2019-11-17 00:15
> Howdy y’all, I made a dedicated documentation page just for this, please have a look! https://www.11ty.io/docs/pagination-nav

this link is bad.
NOT FOUND!
We couldn’t find the content you were looking for.

**Comment by Ryuno-Ki** [comment] 2019-11-18 18:58
That's because it moved to https://www.11ty.io/docs/pagination/nav/ by now.
@zachleat Cool URI's don't change ;-) Perhaps you could add a 301 redirect? If not, hack your way [to it using `<meta http-equiv="refresh" content="0;url=https://www.11ty.io/docs/pagination/nav/" />` [like in the old days](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta)

**Comment by clockshark** [comment] 2019-12-05 10:05
how to get get the total number of pages??

**Comment by zachleat** [comment] 2019-12-05 16:50
@clockshark in upcoming v0.10.0 you can use `pagination.pages.length`
