### ISSUE TITLE
Original error stack trace: Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by xplosionmind** [11ty/eleventy#3062] opened 2023-10-06 08:46 UTC
### Operating system

Fedora 38

### Eleventy

2.0.1

### Describe the bug

I do not really know what is happening, so I will just share [the build debug log](https://paste.yunohost.org/raw/hiziheyaji)

### Reproduction steps

Run `ELEVENTY_ENV=development eleventy --serve --watch --incremental`

### Expected behavior

Build should not fail

**Comment by dagnelies** [comment] 2023-10-20 14:27
Same problem here. I guess there is an issue between "require" and "modules"

    > npx @11ty/eleventy
    [11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
    [11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
    [11ty] 2. require() of ES Module /workspaces/app/.eleventy.js from /workspaces/app/node_modules/@11ty/eleventy/src/Util/Require.js not supported.
    [11ty] Instead change the require of .eleventy.js in /workspaces/app/node_modules/@11ty/eleventy/src/Util/Require.js to a dynamic import() which is available in all CommonJS modules. (via Error)
    [11ty] 
    [11ty] Original error stack trace: Error [ERR_REQUIRE_ESM]: require() of ES Module /workspaces/app/.eleventy.js from /workspaces/app/node_modules/@11ty/eleventy/src/Util/Require.js not supported.
    [11ty] Instead change the require of .eleventy.js in /workspaces/app/node_modules/@11ty/eleventy/src/Util/Require.js to a dynamic import() which is available in all CommonJS modules.
    [11ty]     at requireLocal (/workspaces/app/node_modules/@11ty/eleventy/src/Util/Require.js:6:10)
    [11ty]     at TemplateConfig.requireLocalConfigFile (/workspaces/app/node_modules/@11ty/eleventy/src/TemplateConfig.js:287:23)
    [11ty]     at TemplateConfig.mergeConfig (/workspaces/app/node_modules/@11ty/eleventy/src/TemplateConfig.js:334:28)
    [11ty]     at TemplateConfig.getConfig (/workspaces/app/node_modules/@11ty/eleventy/src/TemplateConfig.js:159:26)
    [11ty]     at new Eleventy (/workspaces/app/node_modules/@11ty/eleventy/src/Eleventy.js:109:39)
    [11ty]     at Object.<anonymous> (/workspaces/app/node_modules/@11ty/eleventy/cmd.js:60:16)

**Comment by dagnelies** [comment] 2023-10-20 14:42
Ok, I figured it out, the error happens when the `package.json` has `"type": "module"`.

**Comment by zachleat** [comment] 2023-11-03 21:21
Duplicate of #836, which has been fixed for 3.0.

**Closed** 2023-11-03 21:22 UTC
Labels: duplicate, feature: esm
