### ISSUE TITLE
In a `pagination`-generated page, 11ty no longer has access to collections.

### ISSUE THREAD

**Issue by jdsteinbach** [11ty/eleventy#129] opened 2018-05-21 23:43 UTC
```
@11ty/eleventy@0.3.4
```

I'm generating a blog with 11ty and ran into an issue when I started using [pagination](https://github.com/11ty/eleventy/blob/master/docs/pagination.md).

I've collected all my `/posts/*.md` into `collections.posts` and assigned that to the data:

```md
---
layout: blog
permalink: page/{{pagination.pageNumber}}/index.html
pagination:
  data: collections.posts
  size: 8
---
```

However, when `blog.liquid` tries to render the site header markup on a page built by the `pagination` helper, it fails to access `collections.nav` and the following block doesn't render (it does render correctly on all "normal" posts & pages):

```liquid
{% if collections.nav %}
  <nav />
{% endif %}
```

Am I missing a detail about how the pagination tool works? Thanks!

**Comment by zachleat** [comment] 2018-05-22 00:41
I’m almost certain this is a duplicate of #115.

This will go out with v0.3.5 this week. If you need something today you can point to the master branch on GitHub!

**Comment by jdsteinbach** [comment] 2018-05-22 01:07
Thanks! Yes, sorry - I didn't dig through closed issues before posting. 😔

I'm good to wait for `0.3.5`

**Closed** 2018-05-22 19:39 UTC
Labels: bug, duplicate
