### ISSUE TITLE
`.markdown` files not processed from custom extension alias (v3.0.0-alpha.11 and above)

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#3337] opened 2024-06-27 20:01 UTC
### Operating system

macOS Sonoma 14.5

### Eleventy

v3.0.0-alpha.11+

### Describe the bug

Using any version of `v3.0.0-alpha` after `alpha.10` results in 80% of files no longer being written to disk:

* `Copied 2046 files / Wrote 2647 files in 8.08 seconds (3.1ms each, v3.0.0-alpha.10)`
* `Copied 2046 files / Wrote 556 files in 2.59 seconds (4.7ms each, v3.0.0-alpha.11)`

I thought this might be an issue with incremental builds, but running `eleventy` without any flags gives the same result. 🤷🏼

### Reproduction steps

1. `npm i`
2. `npm start`

### Reproduction URL

https://github.com/paulrobertlloyd/paulrobertlloyd-v4

**Comment by paulrobertlloyd** [comment] 2024-06-27 20:04
(Am just seeing if I can update my build so that it works if the required env variables are not present…)

**Comment by paulrobertlloyd** [comment] 2024-06-27 20:31
Have updated my repo such that if the env variables are not present, the site will still build. Interestingly, even more files (~89%) not get written in this case:

* `Copied 2046 files / Wrote 2318 files in 13.18 seconds (5.7ms each, v3.0.0-alpha.10)`
* `Copied 2046 files / Wrote 227 files in 1.24 seconds (5.5ms each, v3.0.0-alpha.11)`

**Comment by zachleat** [comment] 2024-06-27 21:06
Investigating…

**Comment by zachleat** [comment] 2024-06-27 21:16
This is almost certainly #3302

**Comment by zachleat** [comment] 2024-06-27 21:19
I think it’ll be fixed with an `addTemplateFormats` in your configuration file:

```
eleventy.addTemplateFormats("markdown");
eleventy.addExtension("markdown", { key: "md" });
```

but I haven’t confirmed in your project yet (I’m seeing some other duplicate permalink issues that might be from missing environment variables)

**Comment by paulrobertlloyd** [comment] 2024-06-27 21:27
Ahhh, okay, that makes sense – something to add to the upgrade docs/plugin!

I’m getting the duplicate permalinks error now too, and that’s with the environment variables set. Will did into it, but this wasn’t reported as an error before – might have this been silently erroring until this point?

**Comment by zachleat** [comment] 2024-06-27 21:29
That might be a mistake—I did some changes in that code recently for https://github.com/11ty/eleventy/issues/3327 I might’ve missed something there. That was shipped in `-alpha.14`.

**Comment by paulrobertlloyd** [comment] 2024-06-27 21:37
If it helps, I get `DuplicatePermalinkOutputError` in `alpha.11`.

**Comment by zachleat** [comment] 2024-06-27 21:46
Oh! This is a bug related to #2780. Aliasing extensions should inherit their permalink processing options and it looks like this alias is just using raw permalinks without processing. Filed that one as #3339.

**Comment by paulrobertlloyd** [comment] 2024-06-27 21:48
Using the uncommon-but-Gruber-preferred `.markdown` extension has really thrown some spanners in the works, eh! 😬

**Comment by zachleat** [comment] 2024-06-27 22:16
After fixing #3339, I see a new conflict that I’ll have to dive into tomorrow, nothing is jumping out at me yet:

```
[11ty] Output conflict: multiple input files are writing to `./www/2018/014/n1/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./src/content/notes/2018-01-15-1.markdown
[11ty]   2. ./src/content/notes/2018-01-14-1.markdown (via DuplicatePermalinkOutputError)
```

**Comment by paulrobertlloyd** [comment] 2024-06-27 22:18
That one may very well be timezone dependent; I’ll let you know once `alpha.15` ships.

**Comment by zachleat** [comment] 2024-06-27 22:26
oh—oh no! that’s probably it. Not sure the best way to fix that globally but the brand new https://github.com/11ty/eleventy/issues/867#issuecomment-2195653973 will probably give you an escape hatch, if you’re interested.

**Comment by paulrobertlloyd** [comment] 2024-06-27 22:27
Oooh, that might be just the ticket, thanks!

**Comment by zachleat** [comment] 2024-07-10 17:38
https://github.com/11ty/eleventy/releases/tag/v3.0.0-alpha.15 is now available—going to consider this one resolved unless I hear otherwise, thank you!

**Closed by zachleat** 2024-07-10 17:38 UTC
Labels: education, waiting-to-close, release: canary
