### ISSUE TITLE
Shortcode successfully added but error persist in CLI

### ISSUE THREAD

**Issue by pxwee5** [11ty/eleventy#430] opened 2019-02-27 03:32 UTC
Version 0.7.1.
Not sure why this is happening but I've successfully added and rendered shortcode in my project. But the error continues to show in my terminal. 

Also, I noticed that saving the shortcode file does not trigger Eleventy to re-capture the file again. Eleventy will just refresh with the old shortcode setup. :(

NJK
```
<div class="col w-10/12 md:w-4/12">
            {% feature "Lorem Ipsum", "Everspi citint eum si dolum assequatem et unt in remporeium quia." %}
</div>
```

eleventy.config.js
```
const featureShortCode = require('./shortcodes/feature.js')

eleventyConfig.addShortcode("feature", featureShortCode);
```

Terminal
```
> (unknown path) [Line 12, Column 14]
  unknown block tag: feature (Template render error):
    Template render error: (unknown path) [Line 12, Column 14]
      unknown block tag: feature
```

**Comment by zachleat** [comment] 2019-03-09 02:42
`.eleventy.js` configuration file changes (and dependencies) not updating is filed at #340.

Can you attach a reduced test case of this? We have a lot of tests around Nunjucks shortcodes so this is interesting!

**Comment by zachleat** [comment] 2019-03-23 02:19
I’m guessing this is a duplicate of #340. Sorry about that!

**Comment by zachleat** [comment] 2019-03-23 02:19
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-03-23 02:19 UTC
Labels: duplicate
