### ISSUE TITLE
Including child .md files into a page.

### ISSUE THREAD

**Issue by enzomd** [11ty/eleventy#396] opened 2019-01-31 23:19 UTC
**Files:**
- sections
    - a.md
    - b.md

- pages
    - home.html

What I am trying to do is include all files in sections in home.html, and have them transformed to HTML.

The issue is that if the ".md" files are inside "_includes", they do not get transformed to HTML.

If they are outside "_includes", they are treated as their own HTML pages in the "_site" output, and it seems the only way to include that HTML is as a collection with tags, which loses the ability to reference by file (E.g. include "a.md").

So how do I tell Eleventy "these are parts of a larger page (not standalone pages), and should be transformed to HTML before including them?"

Ideally Id like to give each ".md" file a `layout` that is a `.njk` that wraps the transformed HTML.

Can this be done?

**Related issues**
- https://github.com/11ty/eleventy/issues/148
- https://github.com/11ty/eleventy/issues/189#issuecomment-411544737

**Comment by zachleat** [comment] 2019-02-01 14:39
Good job finding those related issues—thank you!

I think this might be a duplicate of the request at #250? What do you think?

**Comment by enzomd** [comment] 2019-02-01 14:55
Yep looks like the same use case.

I think the core issue is that Eleventy defines the DOM tree as child->...->root, where the child is a single content file, and the root is the <html>.

This works when the child exactly matches 1:1 with end pages.

But I think it should be possible to define pages as root->...->child*, so you can include any number of child nodes in the tree referenced by file, and process them with any template language before they are included in their parent.

I could be wrong as I have only used Eleventy for a few hours.

**Comment by zachleat** [comment] 2019-02-17 14:45
Thank you! Closing as duplicate.

You are only partially right as collections heavily overlap with this functionality!

https://www.11ty.io/docs/collections/

**Closed by zachleat** 2019-02-17 14:45 UTC
