### ISSUE TITLE
Watches .eleventy.js but doesn't reload config

### ISSUE THREAD

**Issue by remy** [11ty/eleventy#450] opened 2019-03-16 11:22 UTC
This caught me out for quite a long time, but it looks like `eleventy --serve` (though tested with `--watch` and same behaviour) doesn't reload the config at all. The watch sees the file changing, but doesn't execute the exported function again.

I've tested this with the following:

```js
module.exports = function(eleventyConfig) {
  console.log('CONFIG LOADED');
  // rest of the config
}
```

First time 11ty is run, I see the console log, when 11ty restarts, there's no log message (which explains why changes to my custom collections weren't being picked up).

I'm working around the issue using nodemon:

```
nodemon --watch .eleventy.js -x 'npx eleventy --serve'
```

…which is a little overkill, but works for the moment.

**Comment by zachleat** [comment] 2019-03-16 11:51
Ah, sorry about this! We believe it's a duplicate of #340 which is slated for release in the next minor version. Thank you for the temporary workaround!

**Comment by zachleat** [comment] 2019-03-21 22:53
Closing as duplicate

**Closed by zachleat** 2019-03-21 22:53 UTC
Labels: duplicate
