### ISSUE TITLE
Add the ability to use Input / Root directory data files

### ISSUE THREAD

**Issue by BrentARitchie** [11ty/eleventy#993] opened 2020-03-03 17:42 UTC
**Is your feature request related to a problem? Please describe.**
I have been trying to create a boiler plate for my future projects with Eleventy and I am trying to ensure that I have sane defaults where this makes sense. So far the use of template and directory data files has proven invaluable. The problem is that I would like to set some defaults for every file generated in the project such as: setting created and modified dates from git if available, setting sitemap priority to 0.7 by default, etc... I tried to achieve this through a data file at the root but I was unable to get it to work. Adding a layout to all files is cumbersome and I feel that a root directory data file would be a much more eloquent solution.

**Describe the solution you'd like**
I want to put an <inputDir>.11tydata.js in to the input directory and have those values propagate down like other directory data files.

**Describe alternatives you've considered**
I have thought of adding a default layout with these settings or taking these settings from global data files, but those two options add a lot of code and aren't as straight forward as a simple data file.

**Additional context**

I have prepared a [small glitch](https://glitch.com/edit/#!/11ty-root-directory-data) that shows what is happening. Go to the console, run Eleventy and inspect the two generated files, notice how the index.html is missing the value from the directory data file.

**Comment by pdehaan** [comment] 2020-03-03 18:02
Ref: #245

**Comment by BrentARitchie** [comment] 2020-03-06 18:02
I just wanted to add that after playing with the 0.11.0 beta, the global eleventyComputed.js file did exactly what I was looking for. I feel that this specific issue will be addressed once 0.11.0 is out officially.

**Comment by zachleat** [comment] 2020-03-09 22:31
I think this is a duplicate of #935 shipping with 0.11.0 but I’ll add to the milestone anyway

**Closed** 2020-03-09 22:31 UTC
Labels: duplicate

**Comment by anaurelian** [comment] 2020-04-15 15:52
> I just wanted to add that after playing with the 0.11.0 beta, the global eleventyComputed.js file did exactly what I was looking for. I feel that this specific issue will be addressed once 0.11.0 is out officially.

Where did you place the the global eleventyComputed.js file? I have tried many ways, and it does not work:

* /src/eleventyComputed.js
* /src/eleventyComputed.11tydata.js
* /src/_data/eleventyComputed.js
* /src/_data/eleventyComputed.11tydata.js

```
module.exports = {
  eleventyComputed: {
    eleventyNavigation: {
      key: data => data.page.url,
      title: data => data.title,
    }
  }
};
```

I'm using v0.11.0-beta.3. Thank you.

**Comment by zachleat** [comment] 2020-05-11 13:37
@anaurelian: `eleventyComputed.js` would go in your Global Data directory, whatever that might be. The default is `_data/` but if you’ve changed the directories in your configuration file, keep that in mind!

**Comment by madsem** [comment] 2022-03-14 13:54
Hmmm, but the original post mentioned putting the file into the `input` directory.
Which is exactly what I need to do atm.

(I write files to the `_data` folder with headless CMS, which is supposed to have it's content in a repository separate from the 11ty boilerplate, and then be merged on deploy...)

But this doesn't work: `./site` is my input directory and I've placed data files in `./site/eleventyComputed.js`, or `./site/site.11tydata.js` and some other ways all of which didn't work.

I'm trying to separate the global data files that are responsible to hold site specific setup data, from the files written by the cms.
