### ISSUE TITLE
Hot reloading of inlined CSS not working

### ISSUE THREAD

**Issue by cgwrench** [11ty/eleventy#2807] opened 2023-02-15 09:54 UTC
### Operating system

Debian 11, running under WSL 2 on Windows 11 Pro (22H2)

### Eleventy

2.0.0

### Describe the bug

I'm struggling to get hot reloading of inlined CSS to work. I've got a minimal reproduction of the issue I'm seeing below. In this setup, I can see that changes to CSS files trigger a rebuild, but I don't see my CSS changes taking effect in the browser following the rebuild.

### Reproduction steps

These steps are a remix of the [getting started guide](https://www.11ty.dev/docs/getting-started/) and [Inline Minified CSS quick tip](https://www.11ty.dev/docs/quicktips/inline-css/).

1. `mkdir hot-reload-repro`

1. `cd hot-reload-repro`

1. `npm init -y`

1. `npm install --save-dev @11ty/eleventy clean-css`

1. Add the following layout as `_includes/base.njk`:

    ```html
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset=utf-8>
        <title>Eleventy hot reload repo</title>

        {% set css %}
        {% include "assets/css/inline.css" %}
        {% endset %}
        <style>
        {{ css | cssmin | safe }}
        </style>
    </head>
    <body>
        {{ content | safe }}
    </body>
    </html>
    ```

1. Add the following, gorgeous, CSS as `assets/css/inline.css`:

    ```css
    body {
        background: red;
    }
    ```

1. Add the following content as `index.md`:

    ```markdown
    ---
    layout: base.njk
    title: Eleventy hot reload repo
    ---
    # {{ title }}
    ```

1. Add the following eleventy configuration as `eleventy.config.js`:

    ```javascript
    const CleanCSS = require("clean-css");

    module.exports = function(eleventyConfig) {
        eleventyConfig.addFilter("cssmin", function(code) {
            return new CleanCSS({}).minify(code).styles;
        });

        eleventyConfig.addWatchTarget("**/*.css");

        return {
            templateFormats: ["md", "njk"],
            markdownTemplateEngine: "njk"
        };
    };
    ```

1. Run Eleventy and watch for changes: `npx @11ty/eleventy --serve`

### Expected behavior

I would expect that making changes to CSS files would trigger a reload, and the updated stlyes to be visible in the browser without needing to refresh the browser.

Following the reproduction steps, above, making a change to the CSS file, e.g. changing the `background-color`, doesn't apply the updated styles. I don't think this is expected, as I've told Eleventy to watch for changes to CSS files using `eleventyConfig.addWatchTarget("**/*.css")`.

I do see a message like:

```    
[11ty][09:14:44.183 UTC] CSS updated without page reload.
```

in the browser console, but the page CSS doesn't actually update[^1].

It's worth nothing that everything seems to work fine if my CSS files live under the `_includes` directory. I think because changes to includes and layouts cause a full reload.

[^1]: It looks like the `eleventy-dev-server` script has [special handling of changed CSS files](https://github.com/11ty/eleventy-dev-server/blob/e8cb274b88c278b17d455dd5dd1b596a14b8581d/client/reload-client.js#L177-L184). I assume that because my CSS changes are inlined, and in the head of the document, the reload client isn't applying the change. However, this is just a guess and might be wildly off the mark.

**Comment by zachleat** [comment] 2023-03-21 18:51
I think this may be related to https://github.com/11ty/eleventy/pull/2867 or #2869. Can you test with `2.0.1-alpha.2`? (or alternatively 2.0.1 when it is released)

**Comment by zachleat** [comment] 2023-03-21 21:14
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Comment by cgwrench** [comment] 2023-03-25 21:25
Hi @zachleat. Thanks for taking the time to look into this.

Unfortunately, this isn't solved with `2.0.1-alpha.2` (I've also tested `2.0.1-alpha.3` and `2.0.1-beta.1`), so I don't think this is a duplicate of #2867 or #2869.

Looking into this again, I've found that the following do work:

1. including my CSS files under the `_includes` directory (I think because changes to includes and layouts cause a full build or  page reload).
2. linking to my CSS files using `<link href="/assets/css/inline.css" rel="stylesheet">`, rather than inlining the CSS (and adding a `eleventyConfig.addPassthroughCopy("assets/css");` to my `eleventy.config.js` file).
3. including some other type of file in my layout (e.g. `{% include "some-text-file.txt" %}` anywhere in my template, and adding `eleventyConfig.addWatchTarget("**/*.txt")` to my `eleventy.config.js` file).

So it looks like this issue is specific to CSS being inlined.

I observed in my first comment that:

> It looks like the eleventy-dev-server script has [special handling of changed CSS files](https://github.com/11ty/eleventy-dev-server/blob/e8cb274b88c278b17d455dd5dd1b596a14b8581d/client/reload-client.js#L177-L184). I assume that because my CSS changes are inlined, and in the head of the document, the reload client isn't applying the change. However, this is just a guess and might be wildly off the mark.

Could this be the cause of what I'm seeing? If not, please let me know if there's anything more I can share to help get to the bottom of this.

Thanks again for looking into this, and thanks for all your hard work on this excellent project!

**Comment by zachleat** [comment] 2023-04-19 16:12
I do think 2.0.1 had a genuine bug with updating layouts. #2903, which is shipping with 2.0.2.

If you want to test it, you can use `npm install github:11ty/eleventy`

**Comment by zachleat** [comment] 2024-06-18 20:03
There were a few things happening here. I now believe this is a duplicate of #701.

You can workaround it by moving your project directory under `~` or using the polling feature of chokidar, example here: https://www.11ty.dev/docs/watch-serve/#advanced-chokidar-configuration

**Closed by zachleat** 2024-06-18 20:03 UTC
Labels: bug, duplicate, bug: --serve restart
