### ISSUE TITLE
Pass-through copy fails: "Eleventy:EleventyErrorHandler Error with passthrough copy"

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy#1864] opened 2021-06-27 22:26 UTC
**Describe the bug**

I'm working on migrating my Jekyll site to 11ty. Here's the open PR so you can clone the branch and test it locally to help me out: https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/pull/91.

When I spin up the server locally (or inspect the deploy logs in Netlify), I see the following errors related to pass-through copying:

```
Eleventy:EleventyErrorHandler Error with passthrough copy: +0ms
  Eleventy:EleventyErrorHandler Having trouble copying './src/_redirects'
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `TemplatePassthroughManagerCopyError` was thrown +1ms
  Eleventy:EleventyErrorHandler (warn stack): TemplatePassthroughManagerCopyError: Having trouble copying './src/_redirects'
  Eleventy:EleventyErrorHandler     at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplatePassthroughManager.js:137:11
  Eleventy:EleventyErrorHandler     at async Promise.all (index 4) +1ms
  Eleventy:EleventyErrorHandler Cannot read property 'sort' of undefined
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `TypeError` was thrown: +1ms
  Eleventy:EleventyErrorHandler (warn stack): TypeError: Cannot read property 'sort' of undefined
  Eleventy:EleventyErrorHandler     at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/recursive-copy/lib/copy.js:90:8
  Eleventy:EleventyErrorHandler     at async Promise.all (index 4) +0ms
  Eleventy:EleventyErrorHandler Unhandled rejection in promise ([object Promise]): +2ms
  Eleventy:EleventyErrorHandler Having trouble copying
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `TemplateWriterWriteError` was thrown +1ms
  Eleventy:EleventyErrorHandler (error stack): TemplateWriterWriteError: Having trouble copying
  Eleventy:EleventyErrorHandler     at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplateWriter.js:194:9 +2ms
  Eleventy:EleventyErrorHandler Having trouble copying './src/_redirects'
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `TemplatePassthroughManagerCopyError` was thrown +1ms
  Eleventy:EleventyErrorHandler (error stack): TemplatePassthroughManagerCopyError: Having trouble copying './src/_redirects'
  Eleventy:EleventyErrorHandler     at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/@11ty/eleventy/src/TemplatePassthroughManager.js:137:11
  Eleventy:EleventyErrorHandler     at async Promise.all (index 4) +0ms
  Eleventy:EleventyErrorHandler Cannot read property 'sort' of undefined
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `TypeError` was thrown: +3ms
  Eleventy:EleventyErrorHandler (error stack): TypeError: Cannot read property 'sort' of undefined
  Eleventy:EleventyErrorHandler     at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/recursive-copy/lib/copy.js:90:8
  Eleventy:EleventyErrorHandler     at async Promise.all (index 4) +1ms
```

When I remove [`src/_redirects`](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/3cd4d5919680e78dfb8896f9c933c643e28aeaf8/src/_redirects) (my Netlify redirects file) and restart the Eleventy server, it proceeds to give me errors for the _next_ pass-through directory. And so on, until I remove [all of the pass-through statements](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/3cd4d5919680e78dfb8896f9c933c643e28aeaf8/.eleventy.js#L26), at which point it runs without these errors.

**But**, at that point, I also get this error:

```
 > Having trouble rendering liquid (and markdown) template ./src/_posts/2020-03-11-how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog.md

`TemplateContentRenderError` was thrown
> document is not defined

`ReferenceError` was thrown:
    ReferenceError: document is not defined
        at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/components/prism-markdown.js:354:24
        at Object.run (/mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:720:6)
        at stringify (/mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:836:11)
        at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:813:10
        at Array.forEach (<anonymous>)
        at stringify (/mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:812:6)
        at stringify (/mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:820:13)
        at /mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:813:10
        at Array.forEach (<anonymous>)
        at Function.stringify (/mnt/c/Users/aleks/Documents/Dev/projects/personal-website/aleksandrhovhannisyan.com/node_modules/prismjs/prism.js:812:6)
Wrote 0 files in 19.55 seconds (v0.12.1)
```

It's strange because I'm not referencing `document` anywhere in my build scripts.

**To Reproduce**

1. Clone my repo: `git clone git@github.com:AleksandrHovhannisyan/aleksandrhovhannisyan.com.git`
2. Check out the `11ty` branch: `git checkout 11ty`.
3. Run `yarn` to install dependencies.
4. Run `yarn debug:eleventy` to run the eleventy server in debug mode.
5. After a few seconds of output, terminate the server and scroll back up to find the light neon text that reads ` Eleventy:EleventyErrorHandler`. There should be several of these errors:

![image](https://user-images.githubusercontent.com/19352442/123561071-5bb99800-d774-11eb-9f94-8d2f428468c1.png)

**Expected behavior**
Pass-through copy should work on these directories and files.

**Environment:**

- OS and Version: Windows 10 (running eleventy via Ubuntu 18.04/WSL). Also fails on Netlify.
- Eleventy Version: 0.12.1

**Additional context**

1. All config-related files can be found in my [`config` directory](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/tree/92f8ee2f8601104354f9eba7f2604e1dda51f45e/config). They are imported into `.eleventy.js`.

2. I tried this in both a separate repo and in my current repo. Both fail when using yarn. Interestingly, when I use pnpm, I do not get this problem. Not sure why, but I doubt that's relevant.

**Comment by pdehaan** [comment] 2021-06-27 22:58
Interesting! I can reproduce the original error locally on macOS with a simple repo (and trying to copy a favicon to my dist folder). What's double interesting is that running w/ `--dryrun` flag doesn't show any errors, while building throws the error (but also copies the file in question to my output folder successfully).

Possibly related, #1038.

**Comment by timkendrick** [comment] 2021-06-27 23:35
Note that the `Cannot read property 'sort' of undefined` errors are due to a bug in `recursive-copy@2.0.12` which was released a few hours ago and has since been deprecated; this bug is fixed in the latest `recursive-copy@2.0.13`. I've pushed a [PR](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/pull/92) which will upgrade the yarn lockfile.

The template errors appear to be due to the prism markdown component and seem to be a separate issue.

**Comment by pdehaan** [comment] 2021-06-28 00:55
Well, well… that explains why the error disappeared after I reinstalled my dependencies. Thanks for the update @timkendrick !

**Comment by AleksandrHovhannisyan** [comment] 2021-06-28 10:52
@timkendrick Thanks for clarifying! Thought I was losing my mind 😄 I'll file a separate issue with prism or in the @11ty/eleventy-plugin-syntaxhighlight repo regarding that second error.

**Closed** 2021-06-28 11:05 UTC
Labels: needs-triage

**Comment by AleksandrHovhannisyan** [comment] 2021-06-28 11:41
Seems the document error was related to the fact that I had nested markdown like this:

`````md
This is my markdown post, and I want to illustrate how someone might include fenced code blocks in markdown:

````
```language
code
````
`````
