### ISSUE TITLE
Use as package within the nodejs application

### ISSUE THREAD

**Issue by opahopa** [11ty/eleventy#1670] opened 2021-03-01 18:48 UTC
Hi!

Is it possible to use `eleventy` as package within the nodejs app?

Ex:
```
const eleventy = require('eleventy');

const config = {}
eleventy.generate(config);
```

**Comment by pdehaan** [comment] 2021-03-01 19:22
I found https://github.com/11ty/11ty-website/issues/516 (request for docs).

I vaguely recall a fleeting post on Twitter (cant remember if it was from [@eleventy_ty](https://twitter.com/eleven_ty) or @zachleat though) on how to use Eleventy as an API. I'll poke around and see if I can remember the API so I can search my mail/twitter.

**Comment by pdehaan** [comment] 2021-03-01 19:26
https://twitter.com/zachleat/status/1358966988203323394

More great info in https://github.com/11ty/eleventy/issues/620.

**Comment by Ryuno-Ki** [comment] 2021-03-01 19:45
You might want to try the master branch / a canary release to test https://github.com/11ty/eleventy/pull/1629

**Comment by pdehaan** [comment] 2021-03-01 23:45
For my own future reference, I found this worked for me (and writes the files to disk); when I installed via <kbd>npm i @11ty/eleventy@canary -D</kbd>:

```js
const Eleventy = require("@11ty/eleventy");

main();

async function main() {
  try {
    const elev = new Eleventy("./src", "./www_api", { quietMode: true });
    await elev.init();
    await elev.write();
  } catch (err) {
    console.error(err);
    process.exitCode = 1;
  }
}
```

**Comment by zachleat** [comment] 2021-03-19 19:05
This is a great collection of resources, thanks y’all!

Going to put this in the 1.0 milestone but officially this is a dupe of https://github.com/11ty/eleventy/issues/620

Please subscribe over there!

**Closed** 2021-03-19 19:05 UTC
Labels: duplicate, education
