### ISSUE TITLE
add support to allow importing JSON in ES Modules through assert

### ISSUE THREAD

**Issue by teotimepacreau** [11ty/eleventy#3557] opened 2024-11-24 10:47 UTC
### Operating system

Debian 12

### Eleventy

Eleventy v3.0.0

### Describe the bug

I want to import `_data_metadata.json` BEFORE build in order to populate feedPlugin options : 

I know that it requires to import the JSON in the config file before any build action but `import metadata from "./_data/metadata.json" assert { type: "json" };` is not supported

``
eleventyConfig.addPlugin(feedPlugin, {
    type: "atom",
    outputPath: metadata.feed.path,
    collection: {
      name: ["posts", "essais"]
    },
    metadata: {
      language: metadata.language,
      title: metadata.title,
      subtitle: metadata.feed.subtitle,
      base: metadata.url,
      author: {
        name: metadata.author.name,
        email: metadata.author.email
      }
    }
  });
  ``

**Comment by zachleat** [comment] 2024-12-12 20:02
Duplicate of #3580, shipping with v3.0.1-alpha.1

**Closed as completed by zachleat** 2024-12-12 20:02 UTC
Labels: duplicate
