### ISSUE TITLE
I get this error while starting the project with npm run dev.

### ISSUE THREAD

**Issue by Bouali-Ramzi** [11ty/eleventy#3261] opened 2024-04-23 16:48 UTC
### Operating system

windows 11

### Eleventy

2.0

### Describe the bug

[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
[11ty] 2. EIO: i/o error, read (via Error)
[11ty]
[11ty] Original error stack trace: Error: EIO: i/o error, read
[11ty]     at Object.readFileSync (node:fs:457:20)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1389:18)
[11ty]     at Module.load (node:internal/modules/cjs/loader:1206:32)
[11ty]     at Module._load (node:internal/modules/cjs/loader:1022:12)
[11ty]     at Module.require (node:internal/modules/cjs/loader:1231:19)
[11ty]     at require (node:internal/modules/helpers:179:18)
[11ty]     at Object.<anonymous> (E:\github\bliss-template\node_modules\rollup-plugin-terser\rollup-plugin-terser.js:1:30)   
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1369:14)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
[11ty]     at Module.load (node:internal/modules/cjs/loader:1206:32)
ERROR: "watch:eleventy" exited with 1.

### Reproduction steps

4. See an error

### Screenshots

node : v20.12.2
npm : v10.5.0

**Comment by zachleat** [comment] 2024-04-24 14:17
Duplicate of #3260

**Closed by zachleat** 2024-04-24 14:17 UTC
Labels: needs-triage

**Comment by Bouali-Ramzi** [comment] 2024-04-24 17:38
thank you for nothing @zachleat

**Comment by zachleat** [comment] 2024-04-25 13:17
@Bouali-Ramzi you opened two identical issues. Unfortunately given the response here I’m going to have to close both issues instead of just this one.
