### ISSUE TITLE
Layout front matter data not available when setting a template's layout through a global data file or a directory data file

### ISSUE THREAD

**Issue by Gadiguibou** [11ty/eleventy#2163] opened 2022-01-09 19:54 UTC
**Describe the bug**
Layout front matter data is incorrectly merged with template front matter data when the layout property is in a global data file, for example, "_data/layout.json".

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new empty eleventy project.
2. Create a new layout `_includes/my_layout.liquid` with contents:
  
    ```
    ---
    test: test
    ---
    <h2>Content from the layout is displayed</h2>
    {{ content }}
    ```
3. Create a global data file `_data/layout.json` with contents: `"my_layout.liquid"`.
4. Create a new template `index.liquid` with contents:

    ```
    ---
    # layout: my_layout.liquid
    ---
    <h1>Value of "test" from layout front matter data: {{ test }}</h1>
    ```
5. Serve the site and notice that the rendered HTML is `<h2>Content from the layout is displayed</h2>\n<h1>Value of "test" from layout front matter data: </h1>`.

**Expected behaviour**
The value of "test" should be displayed in the `<h1>` element.
This is made evident by the behaviour when the layout is explicitly specified in the template (by uncommenting the line in the front matter of `index. liquid` for example).

**Screenshots**
When setting the layout using a global data file:
![image](https://user-images.githubusercontent.com/34945306/148697805-e4f159e1-f5f6-4ee2-a48e-b8f1ff3a47b8.png)
When setting the layout using the template's front matter:
![image](https://user-images.githubusercontent.com/34945306/148697818-1dd4b4b9-a3ab-4f07-9c0c-bec4820dd9d0.png)

**Environment:**

- OS and Version: Linux (Pop!_OS/Ubuntu) 21.10
- Eleventy Version: 1.0.0

**Additional context**
The bug also appears when setting the `layout` property using the following:

- a directory data file
- a global data file
- the configuration API's `addGlobalData`

The bug does **not** appear when setting the `layout` property from the following:

- frontmatter data in the template
- a template data file

**Comment by zachleat** [comment] 2022-02-16 20:53
I believe this is a duplicate of #2145, whose fix will ship with 1.0.1—thank you!

**Closed by zachleat** 2022-02-16 20:53 UTC
Labels: bug, duplicate
