### ISSUE TITLE
Bad reverse filter output because Liquid is outdated

### ISSUE THREAD

**Issue by barcia** [11ty/eleventy#862] opened 2020-01-15 16:55 UTC
**Describe the bug**
When I use the Liquid reverse filter (Not the reverse() function) to revet a collection it works bad if I use more than one time in the website for the same collection.

**To Reproduce**
This is my working example:
```liquid
<!-- notes.html -->
<ul>
    {%- assign notes = collections.notes | reverse -%}
    {%- for entry in notes -%}
        <li>{{ entry.data.title }}</li>
    {%- endfor -%}
</ul>
```
Outputs:
* Note D
* Note C
* Note B
* Note A

But if I use the same code also in other page:
```liquid
<!-- home.html -->
<ul>
    {%- assign notes = collections.notes | reverse -%}
    {%- for entry in notes -%}
        <li>{{ entry.data.title }}</li>
    {%- endfor -%}
</ul>
```
Outputs:
* Note A
* Note B
* Note C
* Note D

**Environment:**

- OS and Version: Mac
- Eleventy Version: 0.10.0

**Additional context**
In the issue https://github.com/11ty/eleventy/issues/532 an user comment the same problem, but he said that is a problema that Liquid solved in the v8.3.2. 

I think that the problem is that 11ty still use the v[6.4.3](https://github.com/11ty/eleventy/blob/master/package.json#L110).

**Comment by samuelpath** [comment] 2020-08-07 09:53
Same issue as #1334 ?

**Comment by Savjee** [comment] 2021-04-14 08:26
Bumped into the same issue. Liquid reverses the collection in place!

"Fixed" it by creating my own filter.

```js
config.addLiquidFilter("reverse", (collection) => {
    const arr = [...collection];
    return arr.reverse();
});
```

**Comment by zachleat** [comment] 2021-07-10 02:44
Duplicate of https://github.com/11ty/eleventy/issues/469 

The major upgrade will ship with 1.0

**Closed** 2021-07-10 02:44 UTC
Labels: duplicate

**Comment by xplosionmind** [comment] 2022-02-18 15:06
Hi, I am using Eleventy 1.0.0 and I am getting this error at build time:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering html template ./pages/filinge.html

`TemplateContentRenderError` was thrown
> Cannot read properties of undefined (reading 'reverse'), file:./pages/filinge.html, line:9

`RenderError` was thrown
> Cannot read properties of undefined (reading 'reverse')

`TypeError` was thrown:
    TypeError: Cannot read properties of undefined (reading 'reverse')
        at reverse (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:3289:14)
        at Object.render (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1914:26)
        at /Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1807:21
        at Array.reduce (<anonymous>)
        at Object.evalValue$$1 [as evalValue] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1806:29)
        at Object.evalValue$$1 [as evalValue] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:3577:26)
        at Object.render (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:2253:30)
        at Object._callee$ (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1851:55)
        at tryCatch (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:108:40)
        at Generator.invoke [as _invoke] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:319:22)
Wrote 0 files in 0.56 seconds (v0.12.1)
```

I tried using @Savjee’s solution by adding his script to my `.eleventy.js`, but nothing changes. Am I doing something wrong? Shouldn’t the problem be fixed without even creating the custom filter?

**Comment by pdehaan** [comment] 2022-02-18 15:23
@xplosionmind Yeah, I'd imagine overriding the `reverse` filter locally using the above solution would override the [built-in LiquidJS `reverse` filter](https://liquidjs.com/filters/reverse.html).

The error almost sounds like your `site.filinge` variable is `undefined`:
> _Cannot read properties of undefined (reading 'reverse')_

Is your repo public? If so I can take a look.
If not, I'd probably start by trying to dump out the contents of `site.filinge` and verify what the contents are.

```js
// .eleventy.js snippet
eleventyConfig.addFilter("inspect", require("util").inspect);
```
Then:
```html
<pre>{{ site.filinge | inspect }}</pre>
```
