### ISSUE TITLE
_site directory not completely rebuilt when running Eleventy

### ISSUE THREAD

**Issue by jeffreysbrother** [11ty/eleventy#744] opened 2019-10-25 16:56 UTC
**Describe the bug**
When running the generator, the content of _site is not compeltely rebuilt. In other words, files that ought to be removed persist after running Eleventy.

**To Reproduce**
1. Create an img/ directory that contains assets of some kind
2. Ensure that **addPassthroughCopy** is used to copy this directory to _site
3. Run the generator (`npx eleventy --watch` or `npx eleventy`).  _site/img/ should now exist
4. Remove the **addPassthroughCopy** method that registers the img/ directory
5. Re-run the generator (starting and stopping Eleventy makes no difference if you're watching assets)

**Expected behavior**
_site/img/ should NOT exist (but it does)

**Environment:**
 - macOS High Sierra
 - Eleventy version 0.9.0

**Comment by jeromecoupe** [comment] 2019-10-30 00:22
If I am not mistaken, Eleventy does not clean the _site directory every time it runs. I generally create a `clean` task to do that suing NPM script, Gulp, etc.

**Comment by jeffreysbrother** [comment] 2019-10-30 16:26
That appears to be the case. But is there a good reason for Eleventy to _not_ carry this out?

**Comment by jeromecoupe** [comment] 2019-10-31 07:43
Some SSG will erase the output directory, others will not. Just a choice, both options have trade-offs.

**Comment by bikingbadger** [comment] 2019-10-31 07:49
I would say that 11ty should not delete everything due to the fact you might be creating other things inside the directory from other sources. Possibly... I'm just trying to thing as to why you wouldn't want a directory removed completely outside your control. You know more or less what's going on but 11ty couldn't be expected to know the same.
As for a flag that would allow this I reckon it could be a good option. Maybe there's already a enhancement request for this?

**Comment by jeromecoupe** [comment] 2019-10-31 08:06
A quick `clean` NPM script will do the job, so I don't personally see the use for a flag.

**Comment by jeffreysbrother** [comment] 2019-11-01 20:10
Given the responses, the following appears to be a decent cross-platform and safe solution:

```js
const del = require('del');

module.exports = function (eleventyConfig) {
     const dirToClean = '_site/*';
     del(dirToClean);

     // rest of .eleventy.js config
};

console.log('Deleting files and directories in', dirToClean);
```

However, it still seems quite odd that eliminating an `addPassthroughCopy` invocation will not result in the elimination of the associated directory within the **_site** directory.

**Comment by bikingbadger** [comment] 2019-11-03 13:25
Thanks for the little piece of code. I might keep that handy for a project one day @jeffreysbrother 
The think is I still wouldn't be comfortable with 11ty simple deleting directories to rebuild them. I'm just afraid of what could go missing by automating this if you are not aware of it.

**Comment by edwardhorsford** [comment] 2019-11-03 13:48
@bikingbadger One thing to keep in mind is that many hosts like Netlify and Heroku will do a full rebuild each time they run - so all files get cleaned automatically.

With that said, I've got a clean step in gulp for when I'm working locally. It might be handy for Eleventy to have something built in for this.

**Comment by bikingbadger** [comment] 2019-11-03 14:32
mmmmm. OK then I guess this could be something to add. Would you think this should be done by default @edwardhorsford ?

**Comment by Ryuno-Ki** [comment] 2019-11-03 19:30
Please, don't wipe the target directory on rebuilds.
I had that experienced with [harp.js](http://harpjs.com/docs/) and had to restore my other services from a backup :-(

**Comment by jeffreysbrother** [comment] 2019-11-06 14:48
@Ryuno-Ki, I'm not very familiar with a scenario such as this, but I understand now why the target directory ought not be wiped in certain cases.

How about this alternative: Instead of wiping the **_site** directory completely, we at least ensure that an elimination of an `addPassthroughCopy` invocation deletes the corresponding directories that it passes to **_site**.

**Comment by edwardhorsford** [comment] 2019-11-06 17:19
My thoughts would be that *if* this existed, it should be an all or nothing thing (wipe the target completely), and configurable (default off).

**Comment by zachleat** [comment] 2019-11-15 03:06
Duplicate of #19!

**Closed by zachleat** 2019-11-15 03:06 UTC
Labels: needs-triage

**Comment by tobx** [comment] 2021-01-20 19:22
@jeffreysbrother 
> ```js
> const del = require('del');
> 
> module.exports = function (eleventyConfig) {
>      const dirToClean = '_site/*';
>      del(dirToClean);
> 
>      // rest of .eleventy.js config
> };
> ```
You might want to use `del.sync` here. This could end in deleting the directory after `11ty` has already generated new content. Unlikely, but better safe than sorry.

**Comment by tobx** [comment] 2021-01-20 19:41
I post my version here again, maybe it helps someone:
```js
const del = require("del");
const path = require("path");

const config = {
  dir: {
    output: "dist",
    // ...
  },
  // ...
};

module.exports = (_eleventyConfig) => {
  const dirToClean = path.join(config.dir.output, "*");
  console.log(del.sync(dirToClean, { dot: true }));
  return config;
};
```
Of course it would be nicer to have a cli flag in `11ty` for this!

**Comment by mariusa** [comment] 2021-03-16 07:56
Thanks, I get
`
`EleventyConfigError` was thrown
> config is not defined

`ReferenceError` was thrown:
    ReferenceError: config is not defined
`

Also tried replacing `config` with `_eleventyConfig`, but `dir` isn't defined.

**Comment by pdehaan** [comment] 2021-03-16 13:30
@mariusa if you paste your .eleventy.js config file, I can help you debug.

**Comment by mariusa** [comment] 2021-03-16 13:46
Thanks, here it is
```
const markdownIt = require("markdown-it")
const markdownItAnchor = require("markdown-it-anchor")
const markdownItFootnote = require("markdown-it-footnote")
const syntaxHighlight = require("@11ty/eleventy-plugin-syntaxhighlight")
const pluginTOC = require('eleventy-plugin-toc')
const del = require('del')
const fs = require('fs')

module.exports = function (eleventyConfig) {

    //console.log('config.dir.output', eleventyConfig)
    // Clean the output directory. https://github.com/11ty/eleventy/issues/744
    //const dirToClean = path.join(eleventyConfig.dir.output, "*")
    //del.sync(dirToClean, { dot: true })
    del.sync('_site/', { dot: true })

    //const pluginTOC = require('eleventy-plugin-nesting-toc')
    eleventyConfig.addPlugin(pluginTOC)

    // Add header anchor and footnotes plugin to Markdown renderer
    const markdownLib = markdownIt({ html: true, linkify: true, typographer: true })
    markdownLib.use(markdownItFootnote).use(markdownItAnchor, {})
    eleventyConfig.setLibrary("md", markdownLib)

    eleventyConfig.addPlugin(syntaxHighlight)


    //copy files to output -- no breaks pages generated in _site!! 
    // eleventyConfig.setTemplateFormats([

    // Copy anything in the assets/ folder verbatim
    eleventyConfig.addPassthroughCopy("./static/")
    //eleventyConfig.addPassthroughCopy("docs")
    // https://www.11ty.dev/docs/copy/#using-globs
    // Find and copy any `jpg` files, maintaining directory structure.
    // eleventyConfig.addPassthroughCopy("**/*.jpg")
    // eleventyConfig.addPassthroughCopy("**/*.gif")
    // eleventyConfig.addPassthroughCopy("**/*.wasm")
    // eleventyConfig.addPassthroughCopy("**/*.crane")
    // eleventyConfig.addPassthroughCopy("**/*.txt")
    // //https://github.com/11ty/eleventy/issues/1663#issuecomment-799869254
    // eleventyConfig.addPassthroughCopy("**/*.js")

    return {
        dir: {
            input: "src",
            //output: "_site" default
            //layouts: "_layouts" default
        }
    }
}
```

**Comment by mariusa** [comment] 2021-03-16 13:48
This doesn't work:
`
console.log('config.dir.output', eleventyConfig)
`

**Comment by pdehaan** [comment] 2021-03-16 14:48
Ah, yeah, I don't think this will work...

```js
const dirToClean = path.join(eleventyConfig.dir.output, "*")
del.sync(dirToClean, { dot: true })
```

... because the `dir.output` isn't defined until the `return {}` statement at the end of the file (and even then, we commented out the `output` and `layouts` key/values because they were the default values, so those values might get converted into `undefined`).

But since you are using the default output directory of `_site`, hardcoding it should work (like you already have):

```js
del.sync('_site/', { dot: true })
```

So if you **don't** want to hardcode the `_site/` path in your config, you could move the returned config object definition into a separate variable near the top of the file and then return that (similar to what @tobx posted above https://github.com/11ty/eleventy/issues/744#issuecomment-763886959:

```js
const config = {
  dir: {
    input: "src",
    output: "_site",
    layouts: "_layouts"
  }
}

const dirToClean = path.join(config.dir.output, "*")
del.sync(dirToClean, { dot: true })

module.exports = function (eleventyConfig) {
  // ...stuff

  return config;
}
```

**Comment by mariusa** [comment] 2021-03-16 14:57
Thanks Peter, that makes sense. I'll stick to the hardcoded value, it's simpler.

As others said, it would be nicer to have a cli flag in 11ty for this, to delete output by default.
