### ISSUE TITLE
Support for "virtual files"

### ISSUE THREAD

**Issue by keithclark** [11ty/eleventy#2691] opened 2022-12-14 13:02 UTC
### Is your feature request related to a problem? Please describe.

I'm writing a plugin that handles automatic generation of content/config based on data set in front matter. The plugin adds a new collection that contains the relevant content and some shortcodes to render the content in various forms (JSON, .js files etc). Content authors can then configure site behaviour using front matter. This all works perfectly.

What I'd like to do is remove the need to have templates for these files in the `/src` directory as they never change and introduce complexity that content authors don't need to concern themselves with. Ideally, the plugin would generate these files at build time and place them directly in the `/public` directory.

I'd like to explore a way to programatically add virtual files to eleventy via config.

### Describe the solution you'd like

In my 11ty config I'd like to be able add a virtual file using an API like:

```js
eleventyConfig.addVirtualFile(virtualFilePath, fileContent);
```

Used like this:

```js
const myFileContents = `---
permalink: "config.json"
---
{%- shortcodeToGenerateContent collections.all -%}
`;

const myShortcode = (collection) => {
  // do things with the collection
}

module.exports = (eleventyConfig) => {
  eleventyConfig.addShortcode('shortcodeToGenerateContent', myShortCode);
  eleventyConfig.addVirtualFile('config.njk', myFileContents);
}
```

### Describe alternatives you've considered

I've looked at using the eleventy events but these happen to late in the build process to be able to generate content from eleventy's data structures.

**Comment by zachleat** [comment] 2022-12-14 14:26
I believe this is a duplicate of https://github.com/11ty/eleventy/issues/1612 though it took me a bit to find it! I like your name “virtual files” better

**Closed** 2022-12-14 14:27 UTC
Labels: duplicate, enhancement
