### ISSUE TITLE
Eleventy Dev Server breaks consumers of importmaps

### ISSUE THREAD

**Issue by p-ob** [11ty/eleventy#2442] opened 2022-06-16 20:46 UTC
**Describe the bug**
When using an importmap and executing `eleventy --serve --watch`, the injected `/.11ty/reload-client.js` module script is appended earlier in the head than the importmap, which voids the importmap from being used. 

This can be worked around by moving the importmap higher up (I currently have it as the first child of the head element), but ideally 11ty could look to inject its module _after_ the importmap script tag if it exists, else follow the current behavior.

Results in:
```
An import map is added after module script load was triggered.
```

**To Reproduce**

1. Spin up a quick 11ty sandbox
2. Add an importmap
3. Add a module script that relies on that importmap with bare path modifiers
4. Open browser devtools and see error

**Expected behavior**
Importmap would come before any injected module scripts, resulting in successful module loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/3483866/174160078-56fd1479-3f2f-466e-b11b-b4dfc6567db4.png)

base.njk layout file head:
![image](https://user-images.githubusercontent.com/3483866/174161220-12f88328-4360-4e71-8b45-3e63e6e4acd4.png)

**Environment:**

- OS and Version: Windows (using WSL and cmd both)
- Eleventy Version: 2.0.0-canary.11

**Additional context**
To work around the issue, you can disable the live reload snippet via [`setServerOptions`](https://www.11ty.dev/docs/watch-serve/#eleventy-dev-server) OR move the importmap to be higher up in the head (I currently have it as the first child of the head element).

**Comment by zachleat** [comment] 2022-06-16 20:54
Unfortunately this is a duplicate of https://github.com/11ty/eleventy-dev-server/issues/31 but you have so much better info in this issue!

Can you this excellent info as a comment over there?

**Closed by zachleat** 2022-06-16 20:54 UTC
Labels: duplicate, needs-triage

**Comment by p-ob** [comment] 2022-06-16 20:59
Ah, thank you! I searched this repo; I should have searched the namespace. Will do!
