### ISSUE TITLE
No rebuild or watch work (Win10 - WSL2)

### ISSUE THREAD

**Issue by roroland** [11ty/eleventy#2187] opened 2022-01-23 00:14 UTC
**Describe the bug**
I make a clean install with 11ty 1.0, No problems during install, I setup the .elevnty.js and run tasks to watch changes with sass. Setup a template, etc
I start Eleventy correctly, but if I make ANY change to md, html or scss it does not rebuild, or watch anything. I have to stop the run task and restart the task again to see my changes.
I've tried every tutorial, tip and post I found on internet... it just not working for me, please be kind :/

**To Reproduce**
This is my .eleventy.js file

```
  module.exports = function (eleventyConfig) {

    eleventyConfig.addWatchTarget("./src/sass/");
    eleventyConfig.addPassthroughCopy("./src/css/");
    eleventyConfig.setBrowserSyncConfig({
      files: './_site/css/**/*.css',
    });

    return {
      dir: {
        input: "src",
        output: "_site"
      }
    }
  }
```
And my package.json

{
  "name": "aes",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch:sass": "npx sass src/sass:_site/css --watch",
    "build:sass": "sass src/sass:_site/css",
    "watch:eleventy": "npx @11ty/eleventy --serve",
    "build:eleventy": "eleventy",
    "start": "npm-run-all build:sass --parallel watch:eleventy",
    "build": "npm-run-all build:*"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@11ty/eleventy": "^1.0.0"
  },
  "dependencies": {
    "npm-run-all": "^4.1.5",
    "sass": "^1.49.0"
  }
}

**Expected behavior**
It does not rebuild, or watch anything on my project.

**Screenshots**
Site structure
![sitestructure](https://user-images.githubusercontent.com/200220/150659608-bd2e9b87-48dc-4aec-b9db-c1560271c54f.jpg)

**Environment:**

- OS and Version: Windows 10 / WSL 2

**Comment by roroland** [comment] 2022-01-26 21:15
I was able to watch correctly my sass files changing to node-sass so apparently that part was some wrong configuration.
**But I can't make 11ty watch any file change... If I update anything it doesn't copy the file to me _site folder, it doesn't do anything, I have to stop the npm run and start all over  @zachleat please help me**

I think my project setup couldn't be simpler
![currentstate](https://user-images.githubusercontent.com/200220/151247779-3c12eeb1-afc8-4ee7-aa2c-1ce0287d0617.jpg)


`  module.exports = function (eleventyConfig) {
    eleventyConfig.addPassthroughCopy("src/css/");    
    eleventyConfig.addPassthroughCopy("src/images/");    
    eleventyConfig.addWatchTarget("src/scss/");
    eleventyConfig.setBrowserSyncConfig({
      files: './_site/css/**/*.css',
    });

    return {
      passthroughtFileCopy: true,
      markdownTemplateEngine: "html",
      templateFormats:["html", "njk", "md"],
      dir: {
        input: "src",
        output: "_site",
        include: "includes"
      }
    }
  }`

PLEASE HELP

**Comment by roroland** [comment] 2022-03-08 13:34
No one ?

**Comment by zachleat** [comment] 2022-03-08 21:55
Appreciate your patience!

A few folks have commented about this on twitter

https://twitter.com/slecache/status/1481317668141547524
https://twitter.com/jyasskin/status/1331449701430743041
https://twitter.com/roroland/status/1484699570525323266

Folks have had success with using `~` instead

**Comment by ettmetal** [comment] 2022-08-02 14:48
I, too am having this issue. "Just move files" isn't really a workable solution, I have mine there so that both systems can share files, instead of duplicating. (I do access via a '~' path in WSL using symlinks, so I guess it's not the path that seems to cause the issue)

**Comment by zachleat** [comment] 2022-11-18 19:27
Depending on your `.gitignore` entries, this might also be a duplicate of #893

**Comment by zachleat** [comment] 2024-06-18 20:01
Duplicate of #701.

You can workaround it by moving your project directory under `~` or using the polling feature of chokidar, example here: https://www.11ty.dev/docs/watch-serve/#advanced-chokidar-configuration

**Closed by zachleat** 2024-06-18 20:01 UTC
Labels: bug: windows, education, bug: --serve restart, feature: 🪞 ignores
