### ISSUE TITLE
How do we paginate categories.

### ISSUE THREAD

**Issue by clockshark** [11ty/eleventy#793] opened 2019-11-26 07:06 UTC
I came up with a way to paginate my blog home but not my blog categories.
Can someone help?
This is my blog home.
```
---
layout: home
wf: "5d5340185c5ff33536794edc"
title: ClockShark.Com Blog
description: Get the latest information on how to run your field service or construction company better.
permalink: "/Blog/{% if pagination.pageNumber > 0 %}{{ pagination.pageNumber | plus: 1 }}/{% endif %}index.html"
pagination:
  data: collections.blogposts
  size: 12
  alias: posts
---
{% include topbar-blog.html %}
     <div class="blog-home-cat-header">
          <div class="w-container">
               <div class="cat-header-text">Latest News</div>
          </div>
     </div>
    <div class="blog-home-items">
      <div class="w-container">
        <div class="blog-home">
            {% for post in posts %}

              <div class="blog-item">
                <div class="blog-item-top">
                  <div class="catergory-date-header">
                    <div class="catergory-header"><a href="/Blog/Category/{{ post.data.categories | first | default: "Unassigned" }}" class="category-header-link">
                        {{ post.data.categories | first | default: "Unassigned" }}
                    </a></div>
                    <div class="date-header">
                      <div class="text-block-7">{{ post.data.date | date: "%B %e, %Y" }}</div>
                    </div>
                  </div>
                  {% include image.html, image: post.data.featureimage, clip: true, height: 240, width: 380, class: "blog-item-thumb" %}
                  <div class="blog-post-title">
                    <div><a href="{{ post.data.permalink }}" class="link-2">{{ post.data.title }}</a></div>
                  </div>
                  <p class="paragraph-31">{{ post.data.excerpt | strip_html | truncatewords: 25  }}</p>
                </div>
                <div class="blog-post-readmore">
                  <div><a href="{{ post.data.permalink }}" class="read-more-link">Read more...</a></div>
                </div>
              </div>

          {% endfor %}
        </div>
        <!-- Pagination links -->
        <div class="page-selector">
          {% if pagination.previousPageHref %}
            <a href="{{ pagination.previousPageHref }}" class="page-numbers">
              Previous
            </a>
          {% else %}
            <span class="page-numbers">Previous</span>
          {% endif %}
          <span class="page-numbers ">
            Page: {{ pagination.pageNumber | plus: 1 }} of {{ pagination.items | size }}
          </span>
          {% if pagination.nextPageHref %}
            <a href="{{ pagination.nextPageHref }}" class="page-numbers">Next</a>
          {% else %}
            <span class="page-numbers">Next</span>
          {% endif %}
        </div>
      </div>
    </div>
```

and this is my category home

```
--
pagination:
  data: collections
  size: 1
  alias: tag
  filter:
    - all
    - nav
    - post
    - posts
    - blogposts
    - featurepages
permalink: /Blog/Category/{{ tag }}/
layout: home
renderData:
  title: "Category “{{ tag }}”"
  permalink: /Blog/Category/{{ tag }}/
---
     {% include topbar-blog.html %}
          <div class="blog-home-cat-header">
               <div class="w-container">
                    <div class="cat-header-text">{{ tag }}</div>
               </div>
          </div>
          <div class="blog-home-items">
            <div class="w-container">
              <div class="blog-home">
                  {% assign posts = collections[tag] | reverse %}
                  {% for post in posts %}

                    <div class="blog-item">
                      <div class="blog-item-top">
                        <div class="catergory-date-header">
                          <div class="catergory-header"><a href="{{ post.url }}" class="category-header-link">
                            {{ tag }}
                          </a></div>
                          <div class="date-header">
                            <div class="text-block-7">{{ post.data.date | date: "%B %e, %Y" }}</div>
                          </div>
                        </div>
                        {% include image.html, image: post.data.featureimage, clip: true, height: 240, width: 380, class: "blog-item-thumb" %}
                        <div class="blog-post-title">
                          <div><a href="{{ post.url }}" class="link-2">{{ post.data.title }}</a></div>
                        </div>
                        <p class="paragraph-31">{{ post.data.excerpt | strip_html | truncatewords: 20  }}</p>
                      </div>
                      <div class="blog-post-readmore">
                        <div><a href="{{ post.data.url }}" class="read-more-link">Read more...</a></div>
                      </div>
                    </div>

                {% endfor %}
              </div>

            </div>
          </div>
```

**Comment by octoxalis** [comment] 2019-11-26 12:50
```
renderData:
  title: "Category “{{ tag }}”"
  permalink: /Blog/Category/{{ tag }}/
```

You can have a template substitution in front matter only for permalink. Therefore,  `title: "Category “{{ tag }}”"` can't work.

Have a look at [use-data-variables-in-permalink](https://www.11ty.io/docs/permalinks/#use-data-variables-in-permalink)

**Comment by zachleat** [comment] 2019-11-27 03:58
This is a duplicate of #776 I think?

> Ah this is the double-layer pagination problem. There is a way to do this but it isn’t super friendly right now.

> See the example I posted here: #332
> Also upvote #461 if you’d like to see a nicer way integrated into core

**Comment by zachleat** [comment] 2019-11-27 03:58
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Closed by zachleat** 2019-11-27 03:58 UTC
Labels: duplicate, education

**Comment by clockshark** [comment] 2020-07-26 16:16
We figured out a way to do this.  We will publish a document on how to do this.
