### ISSUE TITLE
Eleventy collections do not implicitly add date field to pages for collections to be sorted by Sortable.js

### ISSUE THREAD

**Issue by siddhantyadav** [11ty/eleventy#1460] opened 2020-10-18 21:15 UTC
**Describe the bug**
When I am adding two or more pages to Collections in Eleventy, there is a "Cannot read property 'getTime' of undefined" because there no date field automatically added through the collection which can be used by it inside Sortable.js and hence causing an error.

**To Reproduce**

1. Use the below data set for building multiple eleventy pages using any .njk file, add all the pages to the collection through addAllPagesToCollections = true

let data = [
  {
   name: 'abc'
  },
  {
   name:'xyz'
   }
]

**Expected behavior**
The pages should be built and all the pages can be added to the collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/35149408/96385941-309e9380-1165-11eb-947a-e721c6908afc.png)

**"Problem writing Eleventy templates: (more in DEBUG output)
> Cannot read property 'getTime' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'getTime' of undefined"** 
Error file : node_modules\@11ty\eleventy\src\Util\Sortable.js:98:17)

**Additional context**
If you use the data set below, it works because we can explicitly add a date field and hence the pages can be built and collections can be sorted.

let data = [
  {
   name: 'abc',
   date:'2020-10-07T19:22:49.335Z'
  },
  {
   name:'xyz',
    date:'2020-10-07T19:22:49.335Z'
   }
]

**Comment by arcxyz** [comment] 2020-10-20 17:09
I recently got this error when I was accidentally overriding the `page` variable provided by eleventy on the pagination:
```
---
pagination:
    data: productPages
    size: 1
    alias: page
...
---
```
Using another name for the pagination alias solves the issue for me.

**Comment by haroldao** [comment] 2022-03-07 01:35
> I recently got this error when I was accidentally overriding the `page` variable provided by eleventy on the pagination:
> 
> ```
> ---
> pagination:
>     data: productPages
>     size: 1
>     alias: page
> ...
> ---
> ```
> 
> Using another name for the pagination alias solves the issue for me.

Wowwww thank you 🙌🏽 (I did the same)

**Comment by pdehaan** [comment] 2022-03-07 08:52
Note that while not super obvious, there is a note about that pitfall in https://www.11ty.dev/docs/pages-from-data/ (although if anybody can think of somewhere else in the documentation where that callout would be helpful, let us know).

> _"Note that `page` is a reserved word so you cannot use `alias: page`. Read about Eleventy’s reserved data names in [Eleventy Supplied Data](https://www.11ty.dev/docs/data-eleventy-supplied)."_

**Comment by zachleat** [comment] 2024-07-10 21:28
Duplicate of #3251 and #1173

Also https://github.com/11ty/eleventy/issues/2161#issuecomment-1146697538

**Closed by zachleat** 2024-07-10 21:28 UTC
Labels: duplicate, feature: 📦 pagination, error-messaging
