### ISSUE TITLE
Assign more than one template engine to HTML & allow assigning Markdown

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#1000] opened 2020-03-05 17:12 UTC
**Is your feature request related to a problem? Please describe.**
No, related to a niche experiment I'm undertaking: https://twitter.com/starfalldocs/status/1235602337089150977

**Describe the solution you'd like**
- For 11ty to be able to apply more than one templating engine to an HTML file
- For 11ty to be able to parse markdown inside HTML.

In other words, given a valid HTML file, containing some elements written in Markdown, and some bits of Nunjucks functionality, everything would be turned into valid HTML in the output.

**Additional comments**
It feels like this fits within the 11ty paradigm:

- If "md" is a valid templating language (https://www.11ty.dev/docs/languages/) then why can't we parse markdown inside an HTML file, just like we can any other templating language we set?
- And given that a markdown file can contain another templating lang, and both the markdown and (e.g.) Nunjucks get parsed, it sounds like it's possible to do more than one conversion during build?

Also, this is a daft niche experiment even for me, so this is probably super-low-priority.

**Comment by zachleat** [comment] 2020-03-05 21:40
Seems like this might be a duplicate of https://github.com/11ty/eleventy/issues/148 ?

**Comment by StarfallProjects** [comment] 2020-03-05 21:49
Possibly. The solution in that issue involves more steps right? Wrap md in njk and use an njk shortcode? I was thinking some sort of rendering chain where it takes the html file, processes the njk, then goes over it again to process the md. So all the user would need to do is set the formats in config. They could then write something like this:

```
<h1>A horrible mess</h1>
## Of bits and pieces
**Leads to the meaning of life:** {{ 6*7 }}
```

But no clue which is more elegant/easier to implement.

**Comment by zachleat** [comment] 2020-10-27 16:02
Ah yes, so the difficult piece there is that if you don’t use shortcodes to explicitly declare what the template language is, it’s really hard to guarantee that there won’t be overlap between templating languages.

For example if you try to parse liquid and nunjucks on the same file, the syntax is so close that it’d be a bit confusing as to which was which I think.

I think it’d probably be best to punt this to #148—sorry!

**Closed by zachleat** 2020-10-27 16:02 UTC
Labels: enhancement
