### ISSUE TITLE
Decouple templating engines from eleventy

### ISSUE THREAD

**Issue by b3u** [11ty/eleventy#1144] opened 2020-05-01 20:17 UTC
**Problem**
If I'm working with markdown, I don't need pug, handlebars, *and* nunjucks in my node_modules. It increases install time and folder size.

**Proposals**
A couple ways we could solve this:
1. User installs templating engine and 11ty separately.
2. Engine-specific files & dependencies are moved to separate packages. `@11ty/parser-pug`, for example, can contain the code and dependencies required to use pug as the templating engine.
3. Eleventy CLI downloads templating engine, maybe automatically.

**Comment by b3u** [comment] 2020-05-01 20:19
I think the option 2 is the best, since 3 is complicated and for 1, user might need to download many peer dependencies.

**Comment by Ryuno-Ki** [comment] 2020-05-01 20:20
Duplicate of #779

**Closed** 2020-05-01 20:22 UTC
Labels: enhancement
