### ISSUE TITLE
Trying to paginate a custom collection throws an error

### ISSUE THREAD

**Issue by EdenKupe** [11ty/eleventy#644] opened 2019-08-07 11:45 UTC
Hey guys,

Moving over from Jekyll and WordPress (to my shame) and I love Eleventy so far. I'm using the [Eleventy/Netlify Boilerplate](https://github.com/danurbanowicz/eleventy-netlify-boilerplate) project. My repo is [here](https://github.com/EdenKupe/notTheSky). 

Quick issue I'm facing:

I've added tags to all files in a folder called `augmented` by creating a file titled `augmented.json`. The file contains:

```
{
    "layout": "layouts/augmented.njk",
    "tags": [
      "augmented"
    ]
}
```

It's my understanding that this will then create a custom collection titled `augmented`. I then try to paginate this collection in the corresponding `augmented.njk` template, like so:

```
---
layout: layouts/base.njk
templateClass: tmpl-post
pagination:
  data: collections.augmented
  size: 1
  alias: augmented
---
```

I'm doing this so I can create a nextPage/previousPage link as per issue [#221](https://github.com/11ty/eleventy/issues/211). However, when I attempt to build, I receive the following error:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Dependency Cycle Found: ___TAG___all -> ./posts/augmented/and-he-weeps.md -> ___TAG___augmented -> ./posts/augmented/and-he-weeps.md (Error):
    Error: Dependency Cycle Found: ___TAG___all -> ./posts/augmented/and-he-weeps.md -> ___TAG___augmented -> ./posts/augmented/and-he-weeps.md
        at /usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:28:17
        at Array.forEach (<anonymous>)
        at DFS (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:22:24)
        at /usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:24:9
        at Array.forEach (<anonymous>)
        at DFS (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:22:24)
        at /usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:24:9
        at Array.forEach (<anonymous>)
        at DFS (/usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:22:24)
        at /usr/local/lib/node_modules/@11ty/eleventy/node_modules/dependency-graph/lib/dep_graph.js:229:9
```

The `.md` file which appears in the error is simply the first one in the folder. **The error isn't thrown when I use collections.post but I want to create a next/previous link for this specific collection and not all my posts** Any idea why this is happening?

**Comment by EdenKupe** [comment] 2019-08-07 11:53
Another weird part of this is that calling collections.augmented elsewhere does work. My index page has:

```
<ul id="collectionList">
{%- for post in collections.augmented -%}
  <li><i class="far fa-moon"></i><a href="{{ post.url | url }}">{{ post.data.title }}</a></li>
{%- endfor -%}
</ul>
```

This works perfectly fine.

**Comment by seangwright** [comment] 2019-11-29 23:19
I am experience this same error:

`Dependency Cycle Found: ___TAG___all -> ./src/about/the-team/team-members.njk -> ___TAG___teamMembers -> ./src/about/the-team/team-members.njk`

I have a structure as follows:

```yaml
- /about
 - /the-team
  - /member1
    - member1.md
    - member1.jpg
  - /member2
    - member2.md
    - member2.jpg
  - team-members.njk
  - the-team.json
 - about.njk
 - about.json
```

`about.json`
```json
{
  "layout": "page"
}
```

`the-team.json`
```
{
  "tags": "teamMembers",
  "permalink": false
}
```

`member1.md`
```md
---
firstName: Test
lastName: Member
titleOrPosition: President
leaderType: Director
---

Lorem ipsum...
```

`team-members.njk`
```njk
---
pagination:
  data: collections.teamMembers
  size: 1
  alias: teamMember
  filter:
    - all
permalink: "about/the-team/{{ teamMember.fileSlug | slug }}/"
renderData:
  title: "{{teamMember.data.firstName}} {{teamMember.data.lastName}}"
tags: []
---

<div>
  <a>
    <span style="background-image:url('{{ teamMember.fileSlug }}.jpg');"></span>
    <span>{{ teamMember.data.firstName }}
      {{ teamMember.data.lastName }}</span>
    <span>{{ teamMember.data.leaderType }}</span>
  </a>
  <div>
    <div>
      {{ teamMember.templateContent | safe }}
    </div>
  </div>
</div>
```

What I'm expecting is for `team-members.njk` to be used as the common 'local' layout for all `member*.md` data since all the `member*.md` files inherit the `permalink: false` from `the-team.json`.

I don't understand why this is an issue since `team-members.njk` has `tags: []`, isn't inheriting the `teamMembers` tag from anywhere, and has `all` in the pagination `filter:`

If I add `eleventyExcludeFromCollections: true` to `team-members.njk`, the cyclic dependency error is resolved, but it's not at all clear why this should be required.

---

An aside: Changes to `the-team.json`, `member*.md` files or my `team-members.njk` file do not trigger rebuilds in `--watch` mode, however changes to any of the other files do trigger rebuilds. Weird? Broken?

**Comment by tannerdolby** [comment] 2021-05-25 10:43
Hmm, just tested this out locally and currently we can't paginate a collection without the following error being thrown:

```
Error: Dependency Cycle Found: ___TAG___all ->
```

Paging an object or anything other than collection works as expected. But no matter who you slice it, something is breaking when we pass a collection to the `data` key in `pagination`.

@zachleat ping

**Comment by tobystokes** [comment] 2022-01-20 10:24
I was getting the same error after upgrading from 0.12 -> 1.0

In my case, the collection that failed was caused by the same tag being included by both a directory data file, _and_ in the frontmatter of individual pages. Using frontmatter solely to define tags worked as expected. 

(That doesn't feel like a conclusive bug definition, but may be of interest to others debugging the same error message.)

**Comment by tobystokes** [comment] 2022-01-20 11:34
Aha, because [deep data merge](https://v1-0-0.11ty.dev/docs/data-deep-merge/) is enabled by default in 1.0!

So be aware, if you're adding tags via directory data, be sure to override or at least don't add the same tag again in frontmatter.

**Comment by Stefanye** [comment] 2022-02-23 14:50
I'm trying to achieve something similar, only difference is, that some of my posts are going to have sub pages, some are not. I have to sort them into collections, so the listing should be automatic. ([I've explained my issue here](https://github.com/11ty/eleventy/discussions/2243))

However I'm stuck with using a specific tag only. I get the same error as OP did. I saw @tobystokes's reply about the deep data merge, and I set it to false in my `.eleventy.js` but I keep getting the same error :/ 

[You can check here](https://github.com/Stefanye/schatten.hu/tree/post-pagination) what I'm having so far. My goal is: if the post has more pages, add a pagination, if not, hide it. **_Note, currently throws an error if you try to run it._**
The pagination can be found under `_includes/layouts/project.liquid` (this is my posts' layout file)
The post I want to have more pages chapters is under `posts/bouquet-preview-app-case-study`

**Comment by zachleat** [comment] 2022-05-10 17:46
Unfortunately this issue slipped under the radar—I’m finally circling back through some of the old issues on the tracker but I’d love a confirmation that this old one is still relevant before I start debugging! If I don’t hear anything in the next two weeks, I’ll likely close it as stale—sorry (and thank you!)

**Comment by tobystokes** [comment] 2022-05-11 08:41
I can still recreate the same error message `Dependency Cycle Found: ___TAG___all -> ./src/blog/index.njk -> ___TAG___blog -> ./src/blog/index.nj` (which is the page that does pagination) - not sure it's exactly the same situation as original poster, but quite likely connected.

given blog/a-post.md frontmatter:
```
---
tags: 
 - blog
 - news
 ---
 ```
 combined with data blog/blog.json:
```
{
  "layout": "post.njk",
  "tags": "blog",
}
```
 Having the same tag from both sources causes the error. If I remove the duplicate tag from the frontmatter, all good. 
 With data deep merge enabled, I would expect/hope the two sources to merged nicely*
 (* hmm ok fair enough I wouldn't expect a merged array to remove duplicates. But having a duplicate tag in either the frontmatter or data source alone doesn't cause the cyclical error.)
 
 (but mostly, thanks for 11ty @zachleat !)

**Comment by pdehaan** [comment] 2022-07-11 21:10
@lolaodelola I was able to get your example working (after renaming posts/post.json to a plural posts/posts.json) and adding `eleventyExcludeFromCollections: true` to the posts/post.md front matter (I'm guessing it didn't like trying to recursively paginate over a collection that it is a part of).

```html
---
layout: layouts/default.njk
pagination:
  data: collections.post
  size: 1
  alias: p
eleventyExcludeFromCollections: true
---

<pre>{{ p.data.title }}</pre>
```

**Comment by lolaodelola** [comment] 2022-07-13 15:33
Thanks so much @pdehaan!! I had changed the filename but hadn't added the `eleventyExcludeFromCollections: true`. The error is gone now but the pagination (seemingly) isn't working & no errors. I'll continue to debug, thanks again 😊

**Comment by pdehaan** [comment] 2022-07-13 23:04
@lolaodelola If you post a public repo, I can take a look and help debug.

**Comment by lolaodelola** [comment] 2022-08-12 12:06
@pdehaan Thanks for the offer, I got it working (not sure how lol).

**Comment by zachleat** [comment] 2023-11-11 04:28
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and we will reopen the issue. Thanks!

**Closed by zachleat** 2023-11-11 04:28 UTC
Labels: education, cleanup
