### ISSUE TITLE
Custom collection - can't return an object

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#277] opened 2018-10-16 16:04 UTC
I'm trying to use a custom collection to return an object.

However, I get the following error:
`> collections[collectionName] is not iterable (TypeError)`

The [docs state](https://www.11ty.io/docs/collections/#return-values) *"addCollection callbacks can now return any arbitrary object type and it’ll be available as data in the template. Arrays, strings, objects—have fun with it."* - this makes me think it should be fine to return an object.

I've tested with a fresh install of the base blog and adding a custom collection that returns an empty object, and an object with a key value pair.

For my personal site I've gotten around it by returning the object wrapped in an array. But this means when I access the data or paginate on it, I have to call `collections.data[0]`.

The other thing I got to work was returning a Set - but while Eleventy works with it and does pagination on it, I'm struggling to get Nunjucks to iterate over the set.

**Comment by zachleat** [comment] 2018-11-17 21:20
HMMMM. Are you sure this isn’t a duplicate of #202? Seems like it was fixed in 0.5.3?

**Comment by edwardhorsford** [comment] 2018-11-18 15:50
I'm pretty sure I'm running 0.5.4 - if I go in to `node_modules/@11ty/eleventy/package.json` it says 0.5.4. Anything else I can check?

**Comment by edwardhorsford** [comment] 2018-11-18 16:11
@zachleat - tried with another fresh install of the base blog - [commit here](https://github.com/edwardhorsford/eleventy-base-blog-1/commit/043a100ff3b4f743a564ccaab1dc4e419043f27d). Returning a simple object (commented out) or empty object returns the error `> collections[collectionName] is not iterable (TypeError)`

**Comment by zachleat** [comment] 2018-11-18 19:08
Thanks for double checking! Filed as a bug

**Comment by zachleat** [comment] 2018-11-22 03:51
Look for this in 0.6.0

**Closed** 2018-11-22 03:51 UTC
Labels: bug
