### ISSUE TITLE
inputPathToUrl plugin doesn't respect relative paths for links in non-top level templates

### ISSUE THREAD

**Issue by brianzelip** [11ty/eleventy#3312] opened 2024-06-08 16:24 UTC
### Operating system

macOS Monterey v12.7.3

### Eleventy

3.0.0-alpha.10

### Describe the bug

The plugin requires that links to sibling pages on pages in sub directories be prefaced with the directory chain leading to their sub directory instead of the conventional `./`

### Reproduction steps

1. 11ty v3.0.0-alpha-10 configured with `eleventyConfig.addPlugin(InputPathToUrlTransformPlugin);`
2. An input directory with at least two files at the root where at least one of the pages links to the other, and a sub directory containing at least two files where at least one of the files links to the other, eg:

```
.
├── page1.md
├── index.md
└── about
    ├── page2.md
    └── index.md
```

3. Links to sibling pages, eg:

```md
# index.md

[Page1](./page1.md)
```

```md
# about/index.md

[Page2](./page2.md)
```

### Expected behavior

The `href` value on /index.html is as expected, `/page1/` ✅

#### Expected `href` value on /about/index.html

`/about/page2/` ✅

#### Actual `href` value on /about/index.html

`./page2.md` ❌

#### demo

https://11ty-inputpathtourl-demo.pages.dev

#### code

https://github.com/brianzelip/11ty-inputPathToUrl-demo

### Screenshots

Note that the demo on Cloudflare Pages behaves differently than in local dev mode.

Here is the /about/page2 on Cloudflare showing the top-level index.md in place of the nested /about/index.md (note the URL in the address bar):

<img width="1500" alt="cloudflare" src="https://github.com/11ty/eleventy/assets/3411019/d724cc08-df99-49d3-81db-5bed5c12847a">

Here is local dev:

<img width="1486" alt="local-dev" src="https://github.com/11ty/eleventy/assets/3411019/e1c509ee-30a1-4abc-98ff-3fad47045a26">

In both cases the href value is the same.

**Comment by zachleat** [comment] 2024-06-11 22:05
Correct, correctly the inputPath plugin only supports paths relative from the input directory (preferred) or the project root.

This would be a great thing to add though!

**Comment by brianzelip** [comment] 2024-06-12 10:20
@zachleat here's the solution I've implemented, https://github.com/archivesspace/tech-docs/commit/60d34f6260157cc1317f311cc4e537919c1b7f00.

This allows for pages to be clicked to in both markdown (in an editor, on GitHub.com, etc) and HTML.

A (temporary) demo is up at https://tech-docs-11ty.pages.dev/

**Comment by zachleat** [comment] 2024-09-20 17:07
Duplicate of #3417 which is currently available in the newest alpha release!

**Closed by zachleat** 2024-09-20 17:07 UTC
Labels: enhancement, needs-votes, feature: inputpath-to-url
